import type { Grant } from "./grantsData";

export const grantsClimate: Grant[] = [
  {
    id: 111,
    name: "Breakthrough Energy Fellows",
    organization: "Breakthrough Energy",
    logo: "https://placehold.co/100x100/EEE/999?text=B",
    description:
      "Breakthrough Energy Fellows supports scientists and engineers commercializing clean energy innovations. The 2-year fellowship provides funding, mentorship, and connections to translate lab breakthroughs into climate solutions.",
    fundingAmount: "$250,000+",
    category: "Climate",
    tags: ["Clean Energy", "Climate Tech", "Fellowship", "Global"],
    website: "https://www.breakthroughenergy.org/fellows",
    eligibility: [
      "Scientists, engineers, and entrepreneurs with climate tech innovations",
      "Technology must have potential to reduce GHG emissions by 500M tons/year",
      "Must be at or near proof-of-concept stage",
      "Nominations from partner universities and labs",
    ],
    status: "Active",
    deadline: "2026-10-23",
    ecosystem: "USA",
    highlights: [
      "Founded by Bill Gates",
      "2-year fellowship with $250K+ funding",
      "Access to Breakthrough Energy Ventures ($3.5B fund)",
    ],
  },
  {
    id: 112,
    name: "EIT Climate-KIC Accelerator",
    organization: "EIT Climate-KIC",
    logo: "https://placehold.co/100x100/EEE/999?text=E",
    description:
      "EIT Climate-KIC accelerates climate innovation across Europe. Its startup accelerator provides grants, coaching, and market access to cleantech ventures tackling decarbonization, sustainable materials, and circular economy.",
    fundingAmount: "Up to €95,000",
    category: "Climate",
    tags: ["EU", "Cleantech", "Decarbonization", "Accelerator"],
    website: "https://www.climate-kic.org",
    eligibility: [
      "European cleantech startups or willing to operate in Europe",
      "Solutions addressing climate change mitigation or adaptation",
      "Must complete 3-stage accelerator (each stage unlocks funding)",
      "Open to pre-seed and seed-stage ventures",
    ],
    status: "Active",
    deadline: "2026-10-28",
    ecosystem: "EU",
    highlights: [
      "Europe's largest climate innovation network",
      "3-stage program: €15K → €30K → €50K",
      "4,500+ startups supported since 2010",
    ],
  },
  {
    id: 113,
    name: "Green Climate Fund",
    organization: "UNFCCC",
    logo: "https://placehold.co/100x100/EEE/999?text=G",
    description:
      "The Green Climate Fund is the world's largest climate fund, established by UNFCCC to help developing countries reduce emissions and adapt to climate change. It provides grants, loans, and equity for transformational projects.",
    fundingAmount: "Up to $10M+",
    category: "Climate",
    tags: ["UNFCCC", "Developing Countries", "Climate Adaptation", "Global"],
    website: "https://www.greenclimate.fund",
    eligibility: [
      "Projects in developing countries (GCF-eligible nations)",
      "Must be submitted through accredited entities (governments, NGOs, banks)",
      "Both mitigation and adaptation projects eligible",
      "Readiness grants available for project preparation",
    ],
    status: "Active",
    deadline: "2026-11-02",
    ecosystem: "Global",
    highlights: [
      "$12.8B pledged from 49 countries",
      "209 projects approved in 129 countries",
      "Focus on vulnerable communities and LDCs",
    ],
  },
  {
    id: 114,
    name: "ARPA-E (Clean Energy Innovation)",
    organization: "US Department of Energy",
    logo: "https://placehold.co/100x100/EEE/999?text=A",
    description:
      "ARPA-E funds high-risk, high-reward energy research that traditional funding sources won't support. It backs transformational technologies in solar, storage, bioenergy, nuclear, and grid modernization.",
    fundingAmount: "$500,000-$10M",
    category: "Climate",
    tags: ["USA", "Energy Research", "High-risk", "DOE"],
    website: "https://arpa-e.energy.gov",
    eligibility: [
      "US-based research institutions, universities, and startups",
      "Projects must address specific ARPA-E program topics",
      "Technology must be beyond basic research but pre-commercial",
      "International teams eligible if partnered with US entity",
    ],
    status: "Active",
    deadline: "2026-11-07",
    ecosystem: "USA",
    highlights: [
      "Funded 1,600+ projects across 40+ programs",
      "ARPA-E alumni have raised $14B+ in follow-on funding",
      "129 new companies formed from ARPA-E projects",
    ],
  },
  {
    id: 115,
    name: "Shell GameChanger",
    organization: "Shell",
    logo: "https://placehold.co/100x100/EEE/999?text=S",
    description:
      "Shell GameChanger supports early-stage innovators with unproven ideas that could reshape the energy landscape. It provides proof-of-concept funding, technical expertise, and access to Shell's global infrastructure.",
    fundingAmount: "Up to $250,000",
    category: "Climate",
    tags: ["Energy", "Proof of Concept", "Corporate", "Innovation"],
    website: "https://www.shell.com/gamechanger",
    eligibility: [
      "Innovators and startups with novel energy technology concepts",
      "Ideas must be at early concept or pre-prototype stage",
      "Must address energy transition challenges",
      "Global applicants welcome",
    ],
    status: "Active",
    deadline: "2026-11-12",
    ecosystem: "Global",
    highlights: [
      "Access to Shell's R&D labs and engineers",
      "Non-dilutive proof-of-concept funding",
      "200+ projects funded since inception",
    ],
  },
  {
    id: 116,
    name: "Bloomberg Philanthropies Environment Grants",
    organization: "Bloomberg Philanthropies",
    logo: "https://placehold.co/100x100/EEE/999?text=B",
    description:
      "Bloomberg Philanthropies' environment program funds organizations working on clean energy, climate policy, and reducing pollution. It has committed over $500M to environmental causes including the Beyond Carbon initiative.",
    fundingAmount: "Up to $500,000",
    category: "Climate",
    tags: ["Clean Energy", "Policy", "Philanthropy", "Global"],
    website: "https://www.bloomberg.org/environment",
    eligibility: [
      "Nonprofits and organizations with environmental programs",
      "Must address climate change, clean energy, or pollution",
      "Project-based funding with measurable outcomes",
      "Invitation-based for large grants; open RFPs for smaller ones",
    ],
    status: "Invite Only",
    deadline: "2026-11-17",
    ecosystem: "USA",
    highlights: [
      "$500M+ committed to environmental causes",
      "Beyond Carbon campaign to close all US coal plants",
      "Supported clean energy policy in 30+ US states",
    ],
  },
  {
    id: 117,
    name: "Climate50 Innovation Fund",
    organization: "Climate50",
    logo: "https://placehold.co/100x100/EEE/999?text=C",
    description:
      "Climate50 backs early-stage startups building solutions for the 50 most critical climate challenges. It provides grants and pre-seed investment to founders working on energy, food systems, buildings, transport, and nature.",
    fundingAmount: "Up to $100,000",
    category: "Climate",
    tags: ["Pre-seed", "Climate Solutions", "Startups", "Global"],
    website: "https://climate50.com",
    eligibility: [
      "Pre-seed and seed-stage climate tech startups",
      "Must address one of 50 identified critical climate challenges",
      "Global applicants welcome",
      "Strong technical founding team preferred",
    ],
    status: "Active",
    deadline: "2026-11-22",
    ecosystem: "Global",
    highlights: [
      "Focus on the 50 most impactful climate solutions",
      "Both grant and equity investment options",
      "Growing portfolio of 100+ climate startups",
    ],
  },
  {
    id: 118,
    name: "Earthshot Prize",
    organization: "Royal Foundation",
    logo: "https://placehold.co/100x100/EEE/999?text=E",
    description:
      "The Earthshot Prize, founded by Prince William, awards £1M each to 5 winners annually who develop solutions to environmental challenges. Categories: Protect & Restore Nature, Clean Air, Revive Oceans, Build a Waste-Free World, Fix Climate.",
    fundingAmount: "£1,000,000",
    category: "Climate",
    tags: ["Prize", "Environment", "UK", "Nature"],
    website: "https://earthshotprize.org",
    eligibility: [
      "Individuals, teams, or organizations with proven environmental solutions",
      "Must address one of the 5 Earthshot categories",
      "Solutions must be scalable and replicable",
      "Nominations from global network of nominators",
    ],
    status: "Active",
    deadline: "2026-11-27",
    ecosystem: "UK",
    highlights: [
      "5 winners each receive £1M annually until 2030",
      "Global visibility and media coverage",
      "Founded by Prince William, Royal Foundation",
    ],
  },
  {
    id: 119,
    name: "Elemental Excelerator",
    organization: "Elemental Excelerator",
    logo: "https://placehold.co/100x100/EEE/999?text=E",
    description:
      "Elemental Excelerator funds startups deploying climate tech in communities that need it most. It invests in solutions across energy, water, agriculture, and mobility with a focus on equitable deployment.",
    fundingAmount: "Up to $1M",
    category: "Climate",
    tags: ["Climate Tech", "Equity", "Deployment", "Hawaii"],
    website: "https://elementalexcelerator.com",
    eligibility: [
      "Growth-stage climate tech startups ready for deployment",
      "Must have a viable product and early customers",
      "Must commit to deploying in underserved communities",
      "Sectors: energy, water, agriculture, mobility, circular economy",
    ],
    status: "Active",
    deadline: "2026-12-02",
    ecosystem: "USA",
    highlights: [
      "$1M grants for real-world deployment projects",
      "Focus on equitable climate solutions",
      "170+ startups funded, $8B+ in follow-on capital raised",
    ],
  },
  {
    id: 120,
    name: "Patagonia Environmental Grants",
    organization: "Patagonia",
    logo: "https://placehold.co/100x100/EEE/999?text=P",
    description:
      "Patagonia's environmental grants program funds grassroots activism and innovative solutions to the environmental crisis. It supports small, scrappy organizations working on root causes of environmental problems.",
    fundingAmount: "Up to $200,000",
    category: "Climate",
    tags: ["Grassroots", "Activism", "Environment", "Conservation"],
    website: "https://www.patagonia.com/actionworks/grants",
    eligibility: [
      "Small grassroots environmental organizations",
      "Must address root causes of environmental problems",
      "Direct-action campaigns and community-based projects preferred",
      "Applications accepted twice yearly (April and August)",
    ],
    status: "Active",
    deadline: "2026-12-07",
    ecosystem: "Global",
    highlights: [
      "Patagonia gives 1% of sales to environmental causes",
      "$140M+ donated since 1985",
      "Favors bold, direct-action environmental groups",
    ],
  },
];
