import type { Grant } from "./grantsData";

export const grantsResearch: Grant[] = [
  {
    id: 71,
    name: "Fulbright-Nehru Fellowship",
    organization: "USIEF",
    logo: "https://placehold.co/100x100/EEE/999?text=F",
    description:
      "The Fulbright-Nehru Fellowship enables Indian students, scholars, and professionals to study, research, or teach at US institutions. It covers tuition, living expenses, travel, and health insurance for periods ranging from 4 to 9 months.",
    fundingAmount: "Up to $50,000",
    category: "Research",
    tags: ["USA", "Research", "Fellowship", "Academic"],
    website: "https://usief.org.in",
    eligibility: [
      "Indian citizens with strong academic records",
      "Master's degree or equivalent required for most categories",
      "Must return to India after fellowship completion",
      "Application deadline typically in February/June each year",
    ],
    status: "Active",
    deadline: "2026-06-05",
    ecosystem: "USA",
    highlights: [
      "Most prestigious Indo-US academic exchange program",
      "J-1 visa and round-trip airfare included",
      "Over 20,000 Indians have participated since 1950",
    ],
  },
  {
    id: 72,
    name: "Wellcome Trust Research Grants",
    organization: "Wellcome Trust",
    logo: "https://placehold.co/100x100/EEE/999?text=W",
    description:
      "The Wellcome Trust funds bold research to improve health. Its grants support discovery research, technology development, and interventions across biomedical science, population health, humanities, and social science.",
    fundingAmount: "Up to £3M",
    category: "Research",
    tags: ["UK", "Biomedical", "Health Research", "Discovery"],
    website: "https://wellcome.org/grant-funding",
    eligibility: [
      "Researchers at any career stage worldwide",
      "Must be based at an eligible host institution",
      "Research must aim to improve understanding of health",
      "Multiple grant types: Discovery, Career Development, Collaborative",
    ],
    status: "Active",
    deadline: "2027-06-10",
    ecosystem: "UK",
    highlights: [
      "One of the world's largest research funders (£16B+ endowment)",
      "Open to researchers from any country",
      "Flexible funding for 3-8 year projects",
    ],
  },
  {
    id: 73,
    name: "Grand Challenges Explorations",
    organization: "Bill & Melinda Gates Foundation",
    logo: "https://placehold.co/100x100/EEE/999?text=G",
    description:
      "Grand Challenges Explorations funds bold ideas with potential to solve persistent global health and development challenges. It provides seed funding with a simple 2-page application for unconventional approaches.",
    fundingAmount: "Up to $100,000",
    category: "Research",
    tags: ["Global Health", "Innovation", "Seed Funding", "Global"],
    website: "https://gcgh.grandchallenges.org",
    eligibility: [
      "Researchers and innovators from any organization worldwide",
      "No preliminary data required - just a bold idea",
      "Must address specific challenge topics posted each round",
      "Successful Phase 1 projects can receive up to $1M in follow-on funding",
    ],
    status: "Active",
    deadline: "2027-06-15",
    ecosystem: "Global",
    highlights: [
      "Simple 2-page application process",
      "No preliminary data needed",
      "Over 4,600 projects funded in 100+ countries",
    ],
  },
  {
    id: 74,
    name: "CERN Openlab Summer Students",
    organization: "CERN",
    logo: "https://placehold.co/100x100/EEE/999?text=C",
    description:
      "CERN Openlab offers summer student positions and research associateships for students interested in computing, physics, and engineering. Participants work on cutting-edge projects in data science, machine learning, and quantum computing.",
    fundingAmount: "Stipend + travel",
    category: "Research",
    tags: ["Physics", "Computing", "Switzerland", "Research"],
    website: "https://openlab.cern",
    eligibility: [
      "Undergraduate or Master's students in CS, physics, or engineering",
      "Must be enrolled at a university at time of application",
      "9-week summer program at CERN, Geneva",
      "Applications open October-January each year",
    ],
    status: "Active",
    deadline: "2027-06-20",
    ecosystem: "Switzerland",
    highlights: [
      "Work alongside world-class scientists at CERN",
      "Stipend covers living expenses in Geneva",
      "Access to CERN's computing infrastructure",
    ],
  },
  {
    id: 75,
    name: "DAAD Research Grants",
    organization: "DAAD (German Academic Exchange Service)",
    logo: "https://placehold.co/100x100/EEE/999?text=D",
    description:
      "DAAD offers research grants for doctoral candidates, postdocs, and academics to conduct research at German universities and institutions. Grants cover monthly stipend, health insurance, and travel allowance.",
    fundingAmount: "€1,000-€1,300/month",
    category: "Research",
    tags: ["Germany", "Doctoral", "Academic", "Research"],
    website: "https://www.daad.de/go/en/stipa57742121",
    eligibility: [
      "Graduates and PhD students from all countries",
      "Must have a confirmed research supervisor at a German institution",
      "Research period: 1-10 months for short-term, 3-4 years for doctoral",
      "Application deadlines vary by country and program",
    ],
    status: "Active",
    deadline: "2027-06-25",
    ecosystem: "Germany",
    highlights: [
      "World's largest academic exchange organization",
      "German language course funding included",
      "Over 150,000 funded scholars worldwide annually",
    ],
  },
  {
    id: 76,
    name: "Marie Sklodowska-Curie Fellowship",
    organization: "European Commission",
    logo: "https://placehold.co/100x100/EEE/999?text=E",
    description:
      "Marie Curie Fellowships support experienced researchers with cross-border and cross-sector mobility. The Postdoctoral Fellowships fund 1-2 year research projects at European or global institutions with generous living and mobility allowances.",
    fundingAmount: "€5,080/month + allowances",
    category: "Research",
    tags: ["EU", "Postdoctoral", "Mobility", "Research"],
    website: "https://marie-sklodowska-curie-actions.ec.europa.eu",
    eligibility: [
      "PhD holders of any nationality",
      "Must move to a different country than where they've lived for 3+ years",
      "1-2 year research projects",
      "Annual call with September deadline",
    ],
    status: "Active",
    deadline: "2027-06-30",
    ecosystem: "EU",
    highlights: [
      "One of Europe's most prestigious research fellowships",
      "Mobility, family, and special needs allowances included",
      "Success rate ~15% - highly competitive",
    ],
  },
  {
    id: 77,
    name: "Swiss Government Excellence Scholarships",
    organization: "Swiss Confederation",
    logo: "https://placehold.co/100x100/EEE/999?text=S",
    description:
      "Switzerland offers excellence scholarships for foreign researchers and artists to conduct doctoral or postdoctoral research at Swiss public universities. Monthly stipend, tuition waiver, health insurance, and housing allowance included.",
    fundingAmount: "CHF 1,920/month",
    category: "Research",
    tags: ["Switzerland", "Doctoral", "Postdoctoral", "Excellence"],
    website: "https://www.sbfi.admin.ch/en/swiss-government-excellence-scholarships",
    eligibility: [
      "Researchers from 180+ countries including India",
      "Master's degree holders for PhD programs; PhD holders for postdoc",
      "Must be under 35 (PhD) or have received PhD within past 5 years (postdoc)",
      "Application through Swiss embassy in home country",
    ],
    status: "Active",
    deadline: "2027-07-05",
    ecosystem: "Switzerland",
    highlights: [
      "Full tuition waiver at top Swiss universities (ETH, EPFL)",
      "Health insurance and housing allowance included",
      "12-month renewable scholarships",
    ],
  },
  {
    id: 78,
    name: "Humboldt Research Fellowship",
    organization: "Alexander von Humboldt Foundation",
    logo: "https://placehold.co/100x100/EEE/999?text=H",
    description:
      "The Humboldt Research Fellowship supports highly qualified researchers from abroad to carry out long-term research at German institutions. It provides monthly stipends, travel allowances, and language courses for 6-24 month stays.",
    fundingAmount: "€2,670/month",
    category: "Research",
    tags: ["Germany", "Postdoctoral", "Senior Research", "Long-term"],
    website: "https://www.humboldt-foundation.de",
    eligibility: [
      "Postdoctoral researchers with PhD completed within past 4 years",
      "Senior researchers with professor-equivalent positions also eligible",
      "Must have peer-reviewed publications",
      "Applications accepted year-round; review takes 4-7 months",
    ],
    status: "Active",
    deadline: "2027-07-10",
    ecosystem: "Germany",
    highlights: [
      "Lifetime membership in Humboldt network of 30,000+ researchers",
      "Return fellowships for continued collaboration",
      "56 Nobel laureates among Humboldt alumni",
    ],
  },
  {
    id: 79,
    name: "JSPS Fellowship",
    organization: "Japan Society for the Promotion of Science",
    logo: "https://placehold.co/100x100/EEE/999?text=J",
    description:
      "JSPS Postdoctoral Fellowships invite young researchers from abroad to conduct collaborative research in Japan. The program covers round-trip airfare, monthly stipend, research allowance, and overseas travel insurance.",
    fundingAmount: "¥362,000/month",
    category: "Research",
    tags: ["Japan", "Postdoctoral", "Collaborative Research", "Science"],
    website: "https://www.jsps.go.jp/english",
    eligibility: [
      "Researchers who hold a doctoral degree from outside Japan",
      "Must be from a JSPS partner country",
      "12-24 month research period in Japan",
      "Must have a host researcher at a Japanese institution",
    ],
    status: "Active",
    deadline: "2027-07-15",
    ecosystem: "Japan",
    highlights: [
      "Research allowance of ¥150,000/year",
      "Round-trip airfare included",
      "Access to Japan's top research universities",
    ],
  },
  {
    id: 80,
    name: "Newton International Fellowship",
    organization: "Royal Society",
    logo: "https://placehold.co/100x100/EEE/999?text=R",
    description:
      "Newton International Fellowships enable early-career postdoctoral researchers from overseas to work at UK research institutions for 2 years. The program aims to attract the best researchers globally to build lasting connections with UK science.",
    fundingAmount: "£24,000/year + research expenses",
    category: "Research",
    tags: ["UK", "Postdoctoral", "Royal Society", "Science"],
    website: "https://royalsociety.org/grants-schemes-awards/grants/newton-international",
    eligibility: [
      "Non-UK postdoctoral researchers with PhD within past 7 years",
      "Must have support from a UK host institution",
      "All areas of natural sciences, including engineering",
      "Annual deadline in March",
    ],
    status: "Active",
    deadline: "2027-07-20",
    ecosystem: "UK",
    highlights: [
      "2-year fully funded research position in UK",
      "£8,000 research expenses per year",
      "Follow-up funding of £6,000/year for 10 years",
    ],
  },
  {
    id: 131,
    name: "Schmidt Science Fellows",
    organization: "Schmidt Futures",
    logo: "https://placehold.co/100x100/EEE/999?text=S",
    description:
      "Schmidt Science Fellows is a postdoctoral program that supports the next generation of science leaders. Fellows pivot from their PhD discipline to a new field, gaining breadth and building bridges across scientific domains.",
    fundingAmount: "$100,000/year",
    category: "Research",
    tags: ["Postdoctoral", "Interdisciplinary", "Leadership", "Global"],
    website: "https://schmidtsciencefellows.org",
    eligibility: [
      "PhD graduates from any scientific discipline within past 12 months",
      "Must propose research in a field different from their PhD",
      "Nominated by host institutions from 30+ partner universities",
      "Annual cohort of ~30 fellows",
    ],
    status: "Active",
    deadline: "2027-07-25",
    ecosystem: "Global",
    highlights: [
      "Encourages disciplinary pivoting - unique among fellowships",
      "Leadership development alongside research",
      "Partners with Nature Research for professional development",
    ],
  },
  {
    id: 132,
    name: "Simons Foundation Grants",
    organization: "Simons Foundation",
    logo: "https://placehold.co/100x100/EEE/999?text=S",
    description:
      "The Simons Foundation advances the frontiers of research in mathematics and the basic sciences. Its grants support collaboration, curiosity-driven research, and investigations into the fundamental laws of nature.",
    fundingAmount: "Up to $500,000",
    category: "Research",
    tags: ["Mathematics", "Physics", "Basic Science", "Collaboration"],
    website: "https://www.simonsfoundation.org",
    eligibility: [
      "Academic researchers in mathematics, physics, CS, and life sciences",
      "Must be at accredited research institutions",
      "Programs: Investigators, Collaborations, Fellowships",
      "Nominations and direct applications depending on program",
    ],
    status: "Active",
    deadline: "2027-07-30",
    ecosystem: "USA",
    highlights: [
      "One of the largest private funders of basic science",
      "$500M+ annual budget for science and math",
      "Simons Investigators receive $100K/year for 5+ years",
    ],
  },
  {
    id: 133,
    name: "HHMI Investigator Program",
    organization: "Howard Hughes Medical Institute",
    logo: "https://placehold.co/100x100/EEE/999?text=H",
    description:
      "HHMI Investigators are among the most accomplished biomedical researchers in the world. HHMI provides long-term, flexible funding so investigators can take risks and pursue the most important questions in biology and medicine.",
    fundingAmount: "Up to $1M+/year",
    category: "Research",
    tags: ["Biomedical", "Biology", "Long-term", "Elite"],
    website: "https://www.hhmi.org/programs/biomedical-research",
    eligibility: [
      "Faculty at eligible US research institutions",
      "Must be conducting biomedical research",
      "Selection based on potential, not past achievements",
      "Competition held every 3-5 years; ~25 new investigators per cycle",
    ],
    status: "Active",
    deadline: "2027-08-04",
    ecosystem: "USA",
    highlights: [
      "7-year renewable appointments with full salary support",
      "35 HHMI investigators have won Nobel Prizes",
      "Funds the researcher, not a specific project",
    ],
  },
  {
    id: 134,
    name: "Moore Foundation Science Grants",
    organization: "Gordon & Betty Moore Foundation",
    logo: "https://placehold.co/100x100/EEE/999?text=M",
    description:
      "The Moore Foundation's science program supports curiosity-driven research in physics, astronomy, and data-driven discovery. Its grants fund major research initiatives, instrumentation, and emerging fields of science.",
    fundingAmount: "Up to $5M",
    category: "Research",
    tags: ["Physics", "Astronomy", "Data Science", "Instrumentation"],
    website: "https://www.moore.org/programs/science",
    eligibility: [
      "Academic researchers and institutions",
      "Research in physical sciences, astronomy, or data-driven discovery",
      "Emerging field investigators and large-scale projects",
      "Both invited proposals and open calls",
    ],
    status: "Active",
    deadline: "2027-08-09",
    ecosystem: "USA",
    highlights: [
      "$1.5B+ in science grants since founding",
      "Supports Thirty Meter Telescope and LIGO",
      "Moore Inventors Fellows: $825K over 5 years",
    ],
  },
  {
    id: 135,
    name: "Chan Zuckerberg Initiative Science",
    organization: "Chan Zuckerberg Initiative",
    logo: "https://placehold.co/100x100/EEE/999?text=C",
    description:
      "CZI Science funds research to cure, prevent, or manage all diseases by end of century. It supports single-cell biology, infectious disease, neurodegeneration, and AI for biology through grants, tools, and data platforms.",
    fundingAmount: "Up to $500,000",
    category: "Research",
    tags: ["Biomedicine", "AI for Biology", "Single-cell", "Open Science"],
    website: "https://chanzuckerberg.com/science",
    eligibility: [
      "Academic researchers in biomedical sciences",
      "Must align with CZI's focus areas: cell biology, infectious disease, neurodegeneration",
      "Open-science commitment required",
      "Annual calls for specific programs",
    ],
    status: "Active",
    deadline: "2027-08-14",
    ecosystem: "USA",
    highlights: [
      "$5.3B+ committed to science",
      "Built Human Cell Atlas and CellxGene platform",
      "Strong focus on open-source tools and data sharing",
    ],
  },
  {
    id: 136,
    name: "Kavli Foundation Grants",
    organization: "Kavli Foundation",
    logo: "https://placehold.co/100x100/EEE/999?text=K",
    description:
      "The Kavli Foundation supports basic research in astrophysics, nanoscience, neuroscience, and theoretical physics. It funds Kavli Institutes worldwide and awards the prestigious Kavli Prizes biennially.",
    fundingAmount: "Up to $1M",
    category: "Research",
    tags: ["Astrophysics", "Nanoscience", "Neuroscience", "Theoretical Physics"],
    website: "https://kavlifoundation.org",
    eligibility: [
      "Established researchers at Kavli-affiliated or partner institutions",
      "Research in astrophysics, nanoscience, neuroscience, or theoretical physics",
      "Support for 20 Kavli Institutes across 8 countries",
      "Kavli Prize nominations from the scientific community",
    ],
    status: "Active",
    deadline: "2027-08-19",
    ecosystem: "USA",
    highlights: [
      "20 Kavli Institutes at top universities worldwide",
      "Kavli Prize: $1M in astrophysics, nanoscience, neuroscience",
      "Long-term support for foundational research",
    ],
  },
  {
    id: 137,
    name: "Sloan Research Fellowship",
    organization: "Alfred P. Sloan Foundation",
    logo: "https://placehold.co/100x100/EEE/999?text=S",
    description:
      "Sloan Research Fellowships honor early-career scholars of outstanding promise. Fellows receive $75,000 over 2 years to be used flexibly to advance their research. It's one of the most prestigious awards for young scientists.",
    fundingAmount: "$75,000",
    category: "Research",
    tags: ["Early Career", "Prestigious", "STEM", "USA"],
    website: "https://sloan.org/fellowships",
    eligibility: [
      "Early-career faculty within 6 years of first academic appointment",
      "Must hold tenure-track position at a US or Canadian institution",
      "Fields: chemistry, CS, economics, math, neuroscience, ocean sciences, physics",
      "Nomination by department head or senior colleague",
    ],
    status: "Active",
    deadline: "2027-08-24",
    ecosystem: "USA",
    highlights: [
      "55 Sloan Fellows have gone on to win Nobel Prizes",
      "126 fellows selected annually",
      "Unrestricted funding - no reporting requirements",
    ],
  },
  {
    id: 138,
    name: "Packard Fellowship for Science and Engineering",
    organization: "David and Lucile Packard Foundation",
    logo: "https://placehold.co/100x100/EEE/999?text=P",
    description:
      "The Packard Fellowship provides $875,000 over 5 years to early-career scientists and engineers. It's one of the largest nongovernmental fellowships, giving fellows the freedom to pursue creative research directions.",
    fundingAmount: "$875,000",
    category: "Research",
    tags: ["Early Career", "Engineering", "Science", "Prestigious"],
    website: "https://www.packard.org/what-we-fund/science/packard-fellowships-for-science-and-engineering",
    eligibility: [
      "Faculty within first 3 years of tenure-track appointment",
      "Must be at one of 50 invited universities",
      "Natural sciences and engineering fields",
      "Nominated by university - 2 nominees per institution",
    ],
    status: "Active",
    deadline: "2027-08-29",
    ecosystem: "USA",
    highlights: [
      "$875K over 5 years - among the most generous",
      "20 fellows selected annually from 100 nominees",
      "Complete research freedom - no strings attached",
    ],
  },
  {
    id: 139,
    name: "Burroughs Wellcome Fund Career Awards",
    organization: "Burroughs Wellcome Fund",
    logo: "https://placehold.co/100x100/EEE/999?text=B",
    description:
      "BWF provides career development awards at the interface of basic biomedical science and adjacent disciplines. Programs support researchers in infectious disease, climate change & health, and regulatory science.",
    fundingAmount: "Up to $500,000",
    category: "Research",
    tags: ["Biomedical", "Career Development", "Infectious Disease", "USA"],
    website: "https://www.bwfund.org",
    eligibility: [
      "Researchers at US and Canadian institutions",
      "Must be at career transition stage (postdoc → faculty or early faculty)",
      "Multiple programs with different eligibility requirements",
      "Annual deadlines varying by program",
    ],
    status: "Active",
    deadline: "2027-09-03",
    ecosystem: "USA",
    highlights: [
      "5-year awards with flexible spending",
      "Focus on career transitions in biomedical research",
      "Career Awards at the Scientific Interface: $500K over 5 years",
    ],
  },
  {
    id: 140,
    name: "W.M. Keck Foundation Research Grants",
    organization: "W.M. Keck Foundation",
    logo: "https://placehold.co/100x100/EEE/999?text=K",
    description:
      "The Keck Foundation funds large-scale research projects that are too novel or risky for traditional funding. It supports medical research, science & engineering, and education with major grants to accredited institutions.",
    fundingAmount: "Up to $5M",
    category: "Research",
    tags: ["High-risk", "Medical Research", "Engineering", "Large-scale"],
    website: "https://www.wmkeck.org",
    eligibility: [
      "Accredited US universities and research institutions",
      "Projects must be pioneering and unlikely to receive traditional funding",
      "Typically $500K-$5M for research; up to $15M for facilities",
      "Two-stage application process (Phase I concept, Phase II full proposal)",
    ],
    status: "Active",
    deadline: "2027-09-08",
    ecosystem: "USA",
    highlights: [
      "Funds projects that are too risky for NIH/NSF",
      "$1.8B+ in grants since 1954",
      "Built the Keck Observatory - world's largest telescopes",
    ],
  },
];
