import type { Grant } from "./grantsData";

export const grantsGlobalYouth: Grant[] = [
  {
    id: 81,
    name: "Thiel Fellowship",
    organization: "Thiel Foundation",
    logo: "https://placehold.co/100x100/EEE/999?text=T",
    description:
      "The Thiel Fellowship awards $100,000 to young people (under 23) who want to build new things instead of sitting in a classroom. Fellows skip or drop out of college to pursue research, startups, or social ventures.",
    fundingAmount: "$100,000",
    category: "Global Youth",
    tags: ["Entrepreneurship", "Under 23", "Startups", "Global"],
    website: "https://thielfellowship.org",
    eligibility: [
      "Must be 22 years old or younger at time of application",
      "No degree requirement - in fact, fellows often leave college",
      "Must have a bold idea or startup to pursue full-time",
      "Global applicants welcome",
    ],
    status: "Active",
    deadline: "2027-01-11",
    ecosystem: "Global",
    highlights: [
      "$100K over 2 years with no equity taken",
      "Mentorship from Silicon Valley network",
      "Alumni include Vitalik Buterin, Laura Deming, Austin Russell",
    ],
  },
  {
    id: 82,
    name: "YALI (Young African Leaders Initiative)",
    organization: "US State Department",
    logo: "https://placehold.co/100x100/EEE/999?text=Y",
    description:
      "YALI invests in young African leaders through the Mandela Washington Fellowship - a 6-week academic and leadership institute at a US university. It includes networking, mentorship, and seed funding for community projects.",
    fundingAmount: "Fully funded",
    category: "Global Youth",
    tags: ["Africa", "Leadership", "Fellowship", "US Government"],
    website: "https://www.mandelawashingtonfellowship.org",
    eligibility: [
      "Young Africans aged 25-35 from sub-Saharan Africa",
      "Track record of leadership in business, civic engagement, or public management",
      "Demonstrated commitment to giving back to community",
      "Proficiency in English required",
    ],
    status: "Active",
    deadline: "2027-01-16",
    ecosystem: "Global",
    highlights: [
      "All expenses covered including travel, lodging, and meals",
      "6-week program at a top US university",
      "5,400+ fellows across 49 African countries since 2014",
    ],
  },
  {
    id: 83,
    name: "Global Student Entrepreneur Awards",
    organization: "Entrepreneurs' Organization",
    logo: "https://placehold.co/100x100/EEE/999?text=E",
    description:
      "GSEA is the premier global competition for student entrepreneurs. It showcases students who own and operate a business while attending college. Regional winners compete at the global finals for cash prizes and mentorship.",
    fundingAmount: "$25,000",
    category: "Global Youth",
    tags: ["Competition", "Student", "Entrepreneurship", "Global"],
    website: "https://gsea.org",
    eligibility: [
      "Full-time university students (undergraduate or graduate)",
      "Must be the owner/operator of a revenue-generating business",
      "Business must have been operating for at least 6 months",
      "Open to students from any country",
    ],
    status: "Active",
    deadline: "2027-01-21",
    ecosystem: "Global",
    highlights: [
      "Compete against student entrepreneurs from 60+ countries",
      "Mentorship from EO members (14,000+ entrepreneurs)",
      "Global finals at annual EO event",
    ],
  },
  {
    id: 84,
    name: "Echoing Green Fellowship",
    organization: "Echoing Green",
    logo: "https://placehold.co/100x100/EEE/999?text=E",
    description:
      "Echoing Green finds and funds emerging social entrepreneurs with bold ideas for change. The Fellowship provides seed funding, leadership development, and a network of peers working on racial equity, climate, health, and education.",
    fundingAmount: "$90,000",
    category: "Global Youth",
    tags: ["Social Enterprise", "Racial Equity", "Leadership", "Global"],
    website: "https://echoinggreen.org",
    eligibility: [
      "Early-stage social entrepreneurs with an original idea",
      "Organization must be less than 5 years old",
      "Must work full-time on the venture during fellowship",
      "Both individuals ($90K) and partnerships ($180K split) eligible",
    ],
    status: "Active",
    deadline: "2027-01-26",
    ecosystem: "Global",
    highlights: [
      "90% of fellows are people of color",
      "Alumni include founders of Teach For America, SKS Microfinance",
      "2-year fellowship with ongoing alumni network",
    ],
  },
  {
    id: 85,
    name: "Resolution Fellowship",
    organization: "Resolution",
    logo: "https://placehold.co/100x100/EEE/999?text=R",
    description:
      "Resolution supports young social entrepreneurs (18-25) tackling poverty, inequality, and injustice. Fellows receive funding for 12 months, plus mentoring, legal support, and connections to scale their ventures.",
    fundingAmount: "Â£18,000/year",
    category: "Global Youth",
    tags: ["Social Enterprise", "Youth", "UK", "Poverty"],
    website: "https://www.resolutionfoundation.org",
    eligibility: [
      "Aged 18-25 at time of application",
      "Must be based in the UK or addressing UK social issues",
      "Venture must be less than 2 years old",
      "Must commit to working on venture full-time during fellowship",
    ],
    status: "Active",
    deadline: "2027-01-31",
    ecosystem: "UK",
    highlights: [
      "Targeted at 18-25 year old social entrepreneurs",
      "Legal, accounting, and mentoring support included",
      "100+ fellows and counting",
    ],
  },
  {
    id: 86,
    name: "Watson Fellowship",
    organization: "Thomas J. Watson Foundation",
    logo: "https://placehold.co/100x100/EEE/999?text=W",
    description:
      "The Watson Fellowship funds graduating seniors from select US colleges for a year of independent, purposeful exploration outside the United States. It supports personal growth through immersive cultural experiences.",
    fundingAmount: "$36,000",
    category: "Global Youth",
    tags: ["Exploration", "Cultural", "US Colleges", "Global"],
    website: "https://watson.foundation",
    eligibility: [
      "Graduating seniors from 40 designated US colleges",
      "Must propose a year-long project exploring a personal interest abroad",
      "Cannot return to the US during the fellowship year",
      "Must be nominated by their institution",
    ],
    status: "Active",
    deadline: "2027-02-05",
    ecosystem: "USA",
    highlights: [
      "Complete freedom to design your own year abroad",
      "No academic requirements - pursue your passion",
      "3,000+ alumni since 1968",
    ],
  },
  {
    id: 87,
    name: "Ashoka Youth Venture",
    organization: "Ashoka",
    logo: "https://placehold.co/100x100/EEE/999?text=A",
    description:
      "Ashoka's Youth Venture empowers young people (12-20) to launch their own social ventures. It provides seed funding, mentorship, and a global community of young changemakers tackling local and global challenges.",
    fundingAmount: "Up to $3,000",
    category: "Global Youth",
    tags: ["Social Impact", "Youth 12-20", "Changemakers", "Global"],
    website: "https://ashoka.org/en-us/program/youth-venture",
    eligibility: [
      "Young people aged 12-20",
      "Must have an idea for addressing a social problem",
      "Team-based applications encouraged",
      "Global applicants from any country",
    ],
    status: "Active",
    deadline: "2027-02-10",
    ecosystem: "Global",
    highlights: [
      "Open to youth as young as 12",
      "Part of Ashoka's global network of 3,900+ social entrepreneurs",
      "Peer-to-peer mentoring from young changemakers",
    ],
  },
  {
    id: 88,
    name: "Global Good Fund Fellowship",
    organization: "Global Good Fund",
    logo: "https://placehold.co/100x100/EEE/999?text=G",
    description:
      "The Global Good Fund invests in high-potential leaders aged 18-30 who are driving social impact ventures. Fellows receive funding, executive coaching, and a peer network to accelerate their leadership and venture growth.",
    fundingAmount: "$10,000 + coaching",
    category: "Global Youth",
    tags: ["Leadership", "Social Impact", "Coaching", "Global"],
    website: "https://globalgoodfund.org",
    eligibility: [
      "Social entrepreneurs aged 18-30",
      "Must lead an organization creating measurable social impact",
      "Venture must have been operating for at least 1 year",
      "Applications reviewed on a rolling basis",
    ],
    status: "Active",
    deadline: "2027-02-15",
    ecosystem: "Global",
    highlights: [
      "$10,000 grant plus 1-year executive coaching",
      "130+ fellows from 50+ countries",
      "Focus on leadership development alongside venture growth",
    ],
  },
  {
    id: 89,
    name: "Millennium Fellowship",
    organization: "United Nations Academic Impact",
    logo: "https://placehold.co/100x100/EEE/999?text=U",
    description:
      "The UN Millennium Fellowship is a semester-long leadership program for university students addressing the Sustainable Development Goals. Campus Directors lead SDG-aligned projects and receive UN recognition upon completion.",
    fundingAmount: "Recognition + network",
    category: "Global Youth",
    tags: ["UN", "SDGs", "Campus Leadership", "Global"],
    website: "https://www.millenniumfellows.org",
    eligibility: [
      "Full-time undergraduate students at any university worldwide",
      "Must propose a project aligned with UN SDGs",
      "Applications through campus-level selection",
      "Semester-long commitment required",
    ],
    status: "Active",
    deadline: "2027-02-20",
    ecosystem: "Global",
    highlights: [
      "Official UN recognition and certificate",
      "30,000+ fellows from 3,000+ campuses",
      "Builds SDG-focused leadership on campus",
    ],
  },
  {
    id: 90,
    name: "Hult Prize",
    organization: "Hult Prize Foundation",
    logo: "https://placehold.co/100x100/EEE/999?text=H",
    description:
      "The Hult Prize is the world's largest student competition for social enterprise. University teams compete to solve a pressing social challenge, with the winning team receiving $1M in seed funding to launch their venture.",
    fundingAmount: "$1,000,000",
    category: "Global Youth",
    tags: ["Competition", "Social Enterprise", "University", "Global"],
    website: "https://www.hultprize.org",
    eligibility: [
      "Teams of 3-4 university students (undergrad or grad)",
      "Must address the annual challenge theme",
      "Campus, regional, and global rounds",
      "Open to students from any university worldwide",
    ],
    status: "Active",
    deadline: "2027-02-25",
    ecosystem: "Global",
    highlights: [
      "$1M grand prize - largest student competition in the world",
      "300,000+ participants from 150+ countries annually",
      "Called 'Nobel Prize for students' by Clinton Foundation",
    ],
  },
];
