import type { Grant } from "./grantsData";

export const grantsGovernment: Grant[] = [
  {
    id: 51,
    name: "BIRAC BIG Grant",
    organization: "Biotechnology Industry Research Assistance Council",
    logo: "https://placehold.co/100x100/EEE/999?text=B",
    description:
      "The Biotechnology Ignition Grant (BIG) supports biotech startups and entrepreneurs at the proof-of-concept stage. It funds innovative ideas in healthcare, agriculture, industrial biotech, and clean energy with equity-free grants up to â‚¹50 Lakhs over 18 months.",
    fundingAmount: "Up to â‚¹50 Lakhs",
    category: "Government",
    tags: ["Biotech", "Healthcare", "Agriculture", "India"],
    website: "https://birac.nic.in",
    eligibility: [
      "Indian startups, entrepreneurs, or scientists with biotech innovations",
      "Must be at proof-of-concept or early prototype stage",
      "Company must be incorporated in India",
      "Applications reviewed quarterly by expert committee",
    ],
    status: "Active",
    deadline: "2027-03-02",
    ecosystem: "India",
    highlights: [
      "Equity-free grant - no dilution",
      "18-month funding cycle with milestone reviews",
      "Over 700 startups funded since inception",
    ],
  },
  {
    id: 52,
    name: "Startup India Seed Fund Scheme",
    organization: "DPIIT",
    logo: "https://placehold.co/100x100/EEE/999?text=S",
    description:
      "The Startup India Seed Fund Scheme (SISFS) provides financial assistance to startups for proof of concept, prototype development, product trials, market entry, and commercialization. It operates through selected incubators across India.",
    fundingAmount: "Up to â‚¹50 Lakhs",
    category: "Government",
    tags: ["Seed Fund", "Incubator", "Commercialization", "India"],
    website: "https://seedfund.startupindia.gov.in",
    eligibility: [
      "DPIIT-recognized startups not older than 2 years",
      "Must apply through an approved incubator",
      "Grants up to â‚¹20 Lakhs for validation; loans up to â‚¹50 Lakhs for commercialization",
      "Must not have received more than â‚¹10 Lakhs from any other central/state scheme",
    ],
    status: "Active",
    deadline: "2027-03-07",
    ecosystem: "India",
    highlights: [
      "â‚¹945 Crore corpus supporting 3,600+ startups",
      "Operates through 300+ approved incubators",
      "Both grant and convertible debenture options",
    ],
  },
  {
    id: 53,
    name: "NIDHI-PRAYAS",
    organization: "Department of Science & Technology",
    logo: "https://placehold.co/100x100/EEE/999?text=D",
    description:
      "NIDHI-PRAYAS (Promoting and Accelerating Young and Aspiring Innovators and Startups) supports innovators to translate their ideas into prototypes. Located in Technology Business Incubators, it provides grants, mentorship, and access to fabrication labs.",
    fundingAmount: "Up to â‚¹10 Lakhs",
    category: "Government",
    tags: ["Prototyping", "Innovation", "DST", "India"],
    website: "https://nidhi.dst.gov.in/schemes-programmes/nidhiprayas/",
    eligibility: [
      "Indian innovators with ideas at ideation or early prototype stage",
      "Must apply through a PRAYAS center (TBI-hosted)",
      "Individual innovators or teams of up to 3",
      "Ideas must have commercialization potential",
    ],
    status: "Active",
    deadline: "2027-03-12",
    ecosystem: "India",
    highlights: [
      "9-month support program with mentoring",
      "Access to PRAYAS fabrication labs and workshops",
      "Over 30 PRAYAS centers across India",
    ],
  },
  {
    id: 54,
    name: "Atal New India Challenge",
    organization: "AIM, NITI Aayog",
    logo: "https://placehold.co/100x100/EEE/999?text=A",
    description:
      "The Atal New India Challenge (ANIC) invites startups and MSMEs to create market-ready products addressing national challenges. It provides grants for product development in areas like healthcare, mobility, space, agriculture, and clean energy.",
    fundingAmount: "Up to â‚¹1 Crore",
    category: "Government",
    tags: ["Deep Tech", "National Challenges", "NITI Aayog", "India"],
    website: "https://aim.gov.in/atal-new-india-challenge.php",
    eligibility: [
      "Indian startups, MSMEs, or individual innovators",
      "Product must address specific challenge statements published by ANIC",
      "Must have a working prototype or minimum viable product",
      "12-18 month project timeline",
    ],
    status: "Active",
    deadline: "2027-03-17",
    ecosystem: "India",
    highlights: [
      "Grant-based - no equity or repayment required",
      "Mentorship from industry experts",
      "Focus on deployable solutions for national challenges",
    ],
  },
  {
    id: 55,
    name: "TIDE 2.0",
    organization: "MeitY",
    logo: "https://placehold.co/100x100/EEE/999?text=M",
    description:
      "Technology Incubation and Development of Entrepreneurs (TIDE 2.0) by MeitY supports tech startups through financial grants and incubation. It focuses on IoT, AI, blockchain, robotics, and other emerging technologies across India.",
    fundingAmount: "Up to â‚¹7 Crores",
    category: "Government",
    tags: ["MeitY", "IoT", "AI", "Blockchain", "India"],
    website: "https://meity.gov.in",
    eligibility: [
      "Indian tech startups in emerging technology domains",
      "Must be incubated at a MeitY-approved incubation center",
      "Early-stage startups with viable tech prototypes preferred",
      "Grants disbursed in milestones over 2-3 years",
    ],
    status: "Active",
    deadline: "2027-03-22",
    ecosystem: "India",
    highlights: [
      "Supports 51 incubation centers across India",
      "Focus on Tier-2 and Tier-3 city innovation",
      "Equity-free funding with mentorship access",
    ],
  },
  {
    id: 56,
    name: "SERB Core Research Grant",
    organization: "Science & Engineering Research Board",
    logo: "https://placehold.co/100x100/EEE/999?text=S",
    description:
      "The SERB Core Research Grant (CRG) funds investigator-driven basic and applied research proposals in all areas of science and engineering. It supports projects for 3 years with grants covering equipment, consumables, travel, and manpower.",
    fundingAmount: "Up to â‚¹50 Lakhs/year",
    category: "Government",
    tags: ["Research", "Science", "Engineering", "SERB", "India"],
    website: "https://anrf.gov.in/page/english/research_grants",
    eligibility: [
      "Faculty and scientists at recognized Indian institutions",
      "PhD holders with active research positions",
      "Proposals in any area of science and engineering",
      "3-year project duration with annual reviews",
    ],
    status: "Active",
    deadline: "2027-03-27",
    ecosystem: "India",
    highlights: [
      "Open to all science and engineering disciplines",
      "Supports equipment, travel, and research personnel",
      "Rolling applications accepted throughout the year",
    ],
  },
  {
    id: 57,
    name: "CSIR Innovation Award for School Children",
    organization: "Council of Scientific & Industrial Research",
    logo: "https://placehold.co/100x100/EEE/999?text=C",
    description:
      "CSIR recognizes innovative ideas from school students and young researchers. Through its innovation programs and the CSIR-Tech Innovation Fund, it supports early-stage innovations with grants, mentorship, and commercialization assistance.",
    fundingAmount: "Up to â‚¹10 Lakhs",
    category: "Government",
    tags: ["CSIR", "Innovation", "Students", "Research", "India"],
    website: "https://www.csir.res.in/en/awards/csir-innovation-award-school-children-application",
    eligibility: [
      "Indian students and young researchers",
      "Innovations with commercial or societal impact",
      "Must be original work with demonstrable prototype",
      "Support for patent filing included",
    ],
    status: "Active",
    deadline: "2027-04-01",
    ecosystem: "India",
    highlights: [
      "Patent filing and IP support provided",
      "Access to CSIR's network of 38 national labs",
      "Mentorship from senior scientists",
    ],
  },
  {
    id: 58,
    name: "iDEX (Innovations for Defence Excellence)",
    organization: "Ministry of Defence",
    logo: "https://placehold.co/100x100/EEE/999?text=i",
    description:
      "iDEX engages startups and innovators to solve defence and aerospace challenges. Through the Defence Innovation Organisation (DIO), it provides grants for developing indigenous defence technologies across domains like AI, cybersecurity, and autonomous systems.",
    fundingAmount: "Up to â‚¹1.5 Crore",
    category: "Government",
    tags: ["Defence", "Aerospace", "Innovation", "India"],
    website: "https://idex.gov.in",
    eligibility: [
      "Indian startups, MSMEs, and individual innovators",
      "Solutions must address specific defence challenge statements (DISCs/PISCs)",
      "Must be willing to work with Indian Armed Forces for trials",
      "IP remains with the innovator",
    ],
    status: "Active",
    deadline: "2027-04-06",
    ecosystem: "India",
    highlights: [
      "400+ startups engaged across 100+ challenges",
      "IP retention with the innovator",
      "Procurement guarantee for successful products",
    ],
  },
  {
    id: 59,
    name: "AGNIi Mission",
    organization: "Office of the Principal Scientific Adviser",
    logo: "https://placehold.co/100x100/EEE/999?text=A",
    description:
      "Accelerating Growth of New India's Innovations (AGNIi) connects innovators with markets and funding. It acts as a bridge between Indian innovators, industry, and government to scale and commercialize indigenous technologies.",
    fundingAmount: "Project-based",
    category: "Government",
    tags: ["Commercialization", "Innovation", "PSA", "India"],
    website: "https://www.psa.gov.in/agnii-who-we-are",
    eligibility: [
      "Indian innovators with market-ready technologies",
      "Solutions addressing national challenges in health, agriculture, energy, or water",
      "Must have completed prototype or pilot stage",
      "Open to startups, research institutions, and individuals",
    ],
    status: "Active",
    deadline: "2027-04-11",
    ecosystem: "India",
    highlights: [
      "Direct connections to government procurement",
      "Industry partnerships for scaling",
      "3,000+ innovations catalogued on the platform",
    ],
  },
  {
    id: 60,
    name: "MeitY Startup Hub (MSH)",
    organization: "MeitY",
    logo: "https://placehold.co/100x100/EEE/999?text=M",
    description:
      "MeitY Startup Hub is the nodal entity for MeitY's startup initiatives, managing programs like SAMRIDH and Digital India GENESIS. It provides equity-free grants, mentorship, and market access to tech startups across India.",
    fundingAmount: "Up to â‚¹25 Lakhs",
    category: "Government",
    tags: ["MeitY", "Digital India", "Tech Startups", "India"],
    website: "https://msh.meity.gov.in",
    eligibility: [
      "Indian tech startups in software, AI, cybersecurity, or emerging tech",
      "Must apply through MSH programs (SAMRIDH, GENESIS, etc.)",
      "Early-stage startups with demonstrable product",
      "DPIIT recognition preferred",
    ],
    status: "Active",
    deadline: "2027-04-16",
    ecosystem: "India",
    highlights: [
      "Part of Digital India initiative",
      "Access to government pilot opportunities",
      "Network of 100+ partner incubators",
    ],
  },
  {
    id: 61,
    name: "Karnataka IT Startup Policy (KITS)",
    organization: "Karnataka IT Dept",
    logo: "https://placehold.co/100x100/EEE/999?text=K",
    description:
      "Karnataka's IT startup policy offers subsidies, grants, and incentives to tech startups. It provides reimbursement of rent, patent costs, quality testing, marketing, and cloud hosting. Startups also get procurement preference in government tenders.",
    fundingAmount: "Up to â‚¹50 Lakhs",
    category: "Government",
    tags: ["Karnataka", "IT", "Subsidies", "India"],
    website: "https://www.missionstartupkarnataka.org/funding",
    eligibility: [
      "Startups registered in Karnataka with valid DPIIT recognition",
      "Must be operational within Karnataka's jurisdiction",
      "Less than 5 years old at time of application",
      "Annual turnover below â‚¹10 Crore",
    ],
    status: "Active",
    deadline: "2027-04-21",
    ecosystem: "India",
    highlights: [
      "Reimbursement of rent, patents, and marketing costs",
      "Government procurement preference for startups",
      "Dedicated startup cells in 5 districts",
    ],
  },
  {
    id: 62,
    name: "Kerala Startup Mission (KSUM)",
    organization: "Kerala Startup Mission",
    logo: "https://placehold.co/100x100/EEE/999?text=K",
    description:
      "Kerala Startup Mission is the nodal agency for startup activities in Kerala. It runs incubation programs, innovation grants, and seed funding through its network of incubators. It has supported 4,000+ startups since inception.",
    fundingAmount: "Up to â‚¹30 Lakhs",
    category: "Government",
    tags: ["Kerala", "Incubation", "Innovation", "India"],
    website: "https://startupmission.kerala.gov.in",
    eligibility: [
      "Startups registered in Kerala",
      "Must apply through KSUM's incubation network",
      "Technology-based startups preferred",
      "Open to student entrepreneurs through campus programs",
    ],
    status: "Active",
    deadline: "2027-04-26",
    ecosystem: "India",
    highlights: [
      "4,000+ startups supported",
      "Student innovation programs in 300+ colleges",
      "International soft-landing programs available",
    ],
  },
  {
    id: 63,
    name: "West Bengal SKIPP",
    organization: "WB MSME Department",
    logo: "https://placehold.co/100x100/EEE/999?text=W",
    description:
      "The Student and Knowledge-driven Innovation Promotion Program (SKIPP) supports student entrepreneurs in West Bengal. It provides seed grants, mentorship, and incubation support for innovative ideas from college students.",
    fundingAmount: "Up to â‚¹25 Lakhs",
    category: "Government",
    tags: ["West Bengal", "Students", "Innovation", "India"],
    website: "https://msme.wb.gov.in",
    eligibility: [
      "Students enrolled in West Bengal educational institutions",
      "Innovative ideas with commercial potential",
      "Must have institutional support or incubator backing",
      "Open to undergraduate and postgraduate students",
    ],
    status: "Active",
    deadline: "2027-05-01",
    ecosystem: "India",
    highlights: [
      "Targeted at student entrepreneurs",
      "Incubation space provided at partner institutions",
      "Mentorship from industry and academia",
    ],
  },
  {
    id: 64,
    name: "T-Hub Incubation Program",
    organization: "T-Hub Foundation",
    logo: "https://placehold.co/100x100/EEE/999?text=T",
    description:
      "T-Hub in Hyderabad is India's largest technology incubator. It provides funding, mentorship, corporate connections, and international market access to startups across healthcare, fintech, sustainability, and deep tech domains.",
    fundingAmount: "Up to â‚¹25 Lakhs",
    category: "Government",
    tags: ["Telangana", "Incubation", "Deep Tech", "India"],
    website: "https://t-hub.co",
    eligibility: [
      "Indian startups in tech, healthcare, fintech, or sustainability",
      "Must apply during open cohort windows",
      "Early to growth-stage startups",
      "Startups relocating to Hyderabad preferred",
    ],
    status: "Active",
    deadline: "2027-05-06",
    ecosystem: "India",
    highlights: [
      "India's largest technology incubator",
      "Corporate innovation partnerships with 100+ MNCs",
      "International soft-landing programs in 15+ countries",
    ],
  },
  {
    id: 65,
    name: "Maharashtra Startup Yatra",
    organization: "MSINS",
    logo: "https://placehold.co/100x100/EEE/999?text=M",
    description:
      "Maharashtra State Innovation Society (MSINS) runs Startup Yatra to discover grassroots innovators across Maharashtra. Selected startups receive grants, incubation, and government procurement opportunities through the Maharashtra Startup Policy.",
    fundingAmount: "Up to â‚¹15 Lakhs",
    category: "Government",
    tags: ["Maharashtra", "Grassroots", "Innovation", "India"],
    website: "https://msins.in",
    eligibility: [
      "Startups registered in Maharashtra",
      "DPIIT recognition required",
      "Must participate in district-level Startup Yatra events",
      "Social impact startups receive additional preference",
    ],
    status: "Active",
    deadline: "2027-05-11",
    ecosystem: "India",
    highlights: [
      "Covers all 36 districts of Maharashtra",
      "Government procurement preference for winners",
      "Mentor network of 500+ industry experts",
    ],
  },
  {
    id: 66,
    name: "Gujarat iCreate Program",
    organization: "iCreate",
    logo: "https://placehold.co/100x100/EEE/999?text=G",
    description:
      "iCreate is Gujarat's international centre for entrepreneurship and technology. It provides grants, residential incubation, prototyping labs, and market access to hardware and IoT startups. The program runs 6-month cohorts.",
    fundingAmount: "Up to â‚¹10 Lakhs",
    category: "Government",
    tags: ["Gujarat", "Hardware", "IoT", "Prototyping", "India"],
    website: "https://icreate.org.in",
    eligibility: [
      "Hardware, IoT, and deep tech startups",
      "Willing to participate in 6-month residential program in Ahmedabad",
      "Indian and international startups eligible",
      "Must have a working prototype or strong technical concept",
    ],
    status: "Active",
    deadline: "2027-05-16",
    ecosystem: "India",
    highlights: [
      "Residential incubation with prototyping labs",
      "Focus on hardware and IoT startups",
      "Partnerships with international accelerators",
    ],
  },
  {
    id: 67,
    name: "Tamil Nadu Startup Seed Grant",
    organization: "StartupTN",
    logo: "https://placehold.co/100x100/EEE/999?text=T",
    description:
      "StartupTN, the nodal agency for Tamil Nadu's startup ecosystem, provides seed grants, mentorship, and market access. The state policy offers grants for prototyping, patent filing, and marketing to DPIIT-recognized startups.",
    fundingAmount: "Up to â‚¹30 Lakhs",
    category: "Government",
    tags: ["Tamil Nadu", "Seed Grant", "Patents", "India"],
    website: "https://startuptn.in",
    eligibility: [
      "DPIIT-recognized startups registered in Tamil Nadu",
      "Less than 5 years old",
      "Must be incubated at an approved Tamil Nadu incubator",
      "Revenue below â‚¹25 Crore annually",
    ],
    status: "Active",
    deadline: "2027-05-21",
    ecosystem: "India",
    highlights: [
      "Patent cost reimbursement up to â‚¹10 Lakhs",
      "Marketing support up to â‚¹5 Lakhs",
      "Free co-working space at TIDEL parks",
    ],
  },
  {
    id: 68,
    name: "Rajasthan iStart Program",
    organization: "iStart Rajasthan",
    logo: "https://placehold.co/100x100/EEE/999?text=R",
    description:
      "iStart is Rajasthan's flagship startup initiative providing sustenance allowance, seed grants, and incubation support. It offers monthly stipends to founding teams and connects startups with government departments for pilot projects.",
    fundingAmount: "Up to â‚¹25 Lakhs",
    category: "Government",
    tags: ["Rajasthan", "iStart", "Stipend", "India"],
    website: "https://istart.rajasthan.gov.in",
    eligibility: [
      "Startups registered in Rajasthan with iStart recognition",
      "Less than 7 years from incorporation",
      "Must maintain operations in Rajasthan",
      "Open to both product and service startups",
    ],
    status: "Active",
    deadline: "2027-05-26",
    ecosystem: "India",
    highlights: [
      "Monthly sustenance allowance of â‚¹20,000 per co-founder",
      "Government pilot project opportunities",
      "18,000+ startups registered on iStart platform",
    ],
  },
  {
    id: 69,
    name: "AP Innovation Society (APIS) Grant",
    organization: "AP Innovation Society",
    logo: "https://placehold.co/100x100/EEE/999?text=A",
    description:
      "Andhra Pradesh Innovation Society supports startups through grants, incubation, and innovation challenges. It runs sector-specific programs in agritech, healthtech, and edtech with funding support and government market access.",
    fundingAmount: "Up to â‚¹15 Lakhs",
    category: "Government",
    tags: ["Andhra Pradesh", "Agritech", "Healthtech", "India"],
    website: "https://apis.ap.gov.in",
    eligibility: [
      "Startups registered in Andhra Pradesh",
      "Must address challenges in agriculture, health, or education",
      "DPIIT recognition preferred",
      "Must participate in APIS innovation challenges",
    ],
    status: "Active",
    deadline: "2027-05-31",
    ecosystem: "India",
    highlights: [
      "Sector-specific innovation challenges",
      "Government market access for pilots",
      "Partnerships with global accelerators",
    ],
  },
  {
    id: 70,
    name: "Punjab Startup Scheme",
    organization: "Punjab Infotech",
    logo: "https://placehold.co/100x100/EEE/999?text=P",
    description:
      "Punjab's startup and innovation policy provides financial support through seed grants, infrastructure subsidies, and patent reimbursement. The scheme operates through Punjab Infotech and state-designated incubators.",
    fundingAmount: "Up to â‚¹10 Lakhs",
    category: "Government",
    tags: ["Punjab", "Seed Grant", "Infrastructure", "India"],
    website: "https://punjabinfotech.in",
    eligibility: [
      "Startups incorporated in Punjab",
      "DPIIT recognition required",
      "Must not be a subsidiary of an existing large company",
      "Less than 5 years old at time of application",
    ],
    status: "Active",
    deadline: "2027-06-05",
    ecosystem: "India",
    highlights: [
      "Rent and infrastructure subsidy up to â‚¹5 Lakhs",
      "Patent filing reimbursement",
      "Access to Punjab's IT parks at subsidized rates",
    ],
  },
  {
    id: 151,
    name: "SBIR/STTR - America's Seed Fund",
    organization: "U.S. Small Business Administration",
    logo: "https://placehold.co/100x100/EEE/999?text=S",
    description:
      "America's Seed Fund provides non-dilutive federal grants to U.S. startups developing and commercializing innovative technology, marketed jointly across agencies as SBIR (Small Business Innovation Research) and STTR (Small Business Technology Transfer). Funding is phased from proof-of-concept through commercialization.",
    fundingAmount: "$50,000 - $2,000,000",
    category: "Government",
    tags: ["USA", "Non-Dilutive", "Deep Tech", "Federal Grant"],
    website: "https://www.sbir.gov",
    eligibility: [
      "For-profit U.S. entity with fewer than 500 employees",
      "Majority owned and controlled by U.S. citizens or permanent residents",
      "STTR track requires a formal research-institution partnership",
      "Apply through the specific federal agency running each solicitation",
    ],
    status: "Active",
    deadline: "2026-09-30",
    ecosystem: "USA",
    highlights: [
      "No equity taken - fully non-dilutive",
      "Phase I: $50K-$275K; Phase II: $750K-$1.8M",
      "About 400 companies funded annually since 1977",
    ],
  },
  {
    id: 152,
    name: "EIC Accelerator",
    organization: "European Innovation Council",
    logo: "https://placehold.co/100x100/EEE/999?text=E",
    description:
      "The EIC Accelerator (Horizon Europe) helps deep-tech startups and SMEs scale game-changing innovations with a mix of non-dilutive grants and optional equity investment. Grant-only funding covers innovation activities up to TRL 8, with blended grant-plus-equity available for further scale-up.",
    fundingAmount: "Up to €2.5M grant + €0.5M-€10M equity",
    category: "Government",
    tags: ["EU", "Deep Tech", "Non-Dilutive", "Scale-up"],
    website: "https://eic.ec.europa.eu/eic-funding-opportunities/eic-accelerator_en",
    eligibility: [
      "Startups, SMEs, and small mid-caps from EU or Horizon Europe associated countries",
      "Innovation must be high-risk, high-impact, and ahead of the market",
      "Open topic (any tech field) or predefined EIC Challenges tracks",
      "Periodic cut-off dates for full proposals after a short-form review",
    ],
    status: "Active",
    deadline: "2026-10-07",
    ecosystem: "Europe",
    highlights: [
      "Grant-only option avoids dilution entirely up to TRL 8",
      "61 startups funded in a single round for ~€467M (Feb 2026)",
      "Includes EIC Trusted Investor Network access",
    ],
  },
  {
    id: 153,
    name: "NRC IRAP",
    organization: "National Research Council Canada",
    logo: "https://placehold.co/100x100/EEE/999?text=N",
    description:
      "The Industrial Research Assistance Program (IRAP) is Canada's leading government funding and advisory program for small and medium businesses developing and commercializing new technology, pairing project funding with a dedicated Industrial Technology Advisor.",
    fundingAmount: "Project-based, typically up to $500,000 CAD",
    category: "Government",
    tags: ["Canada", "SME", "Advisory", "Non-Dilutive"],
    website: "https://nrc.canada.ca/en/support-technology-innovation",
    eligibility: [
      "Canadian-incorporated for-profit business with up to 500 FTEs",
      "Technology-driven product or service with commercialization potential",
      "Engagement with an IRAP advisor is required before funding",
      "Continuous intake - no fixed application deadline",
    ],
    status: "Active",
    deadline: "2026-12-31",
    ecosystem: "Canada",
    highlights: [
      "Combines funding with hands-on advisory support",
      "Can also fund hiring recent graduates to offset costs",
      "Rolling, continuous-intake applications",
    ],
  },
  {
    id: 154,
    name: "Israel Innovation Authority Startup Fund",
    organization: "Israel Innovation Authority",
    logo: "https://placehold.co/100x100/EEE/999?text=I",
    description:
      "A non-dilutive co-investment fund that matches private capital in pre-seed, seed, and Round A rounds for Israeli tech startups, without taking equity or voting rights. Extra grant percentage is available for underrepresented founders or periphery-based companies.",
    fundingAmount: "Up to NIS 15,000,000",
    category: "Government",
    tags: ["Israel", "Non-Dilutive", "Co-Investment", "Early Stage"],
    website: "https://innovationisrael.org.il/en/programs/startup-fund/",
    eligibility: [
      "Israeli-incorporated early-stage tech startup",
      "Requires matched private investment in the same round",
      "Pre-Seed: up to 60% grant; Seed: up to 50%; Round A: up to 30%",
      "Additional grant boost for underrepresented founders or periphery regions",
    ],
    status: "Active",
    deadline: "2026-11-15",
    ecosystem: "Israel",
    highlights: [
      "No equity or voting rights taken by the Authority",
      "Scales from pre-seed through Round A",
      "Extra 10% grant for underrepresented founders/periphery",
    ],
  },
  {
    id: 155,
    name: "Innovate UK Smart Grants",
    organization: "UK Research and Innovation (UKRI)",
    logo: "https://placehold.co/100x100/EEE/999?text=U",
    description:
      "Smart Grants fund original, high-impact UK innovations across any sector with a clear route to commercialisation and strong UK economic benefit. The programme is being restructured with new tailored funding products for startups and SMEs, so check the Innovation Funding Service for the current round before applying.",
    fundingAmount: "£100,000 - £1,000,000",
    category: "Government",
    tags: ["UK", "SME", "R&D", "Non-Dilutive"],
    website: "https://www.ukri.org/councils/innovate-uk/guidance-for-applicants/guidance-for-specific-funds/smart-innovation-funding-guidance/",
    eligibility: [
      "UK-registered organisation with project work carried out in the UK",
      "At least one SME must lead or partner on the project",
      "Innovation must be genuinely new and ahead of the market",
      "Rounds currently being redesigned - confirm live call details before applying",
    ],
    status: "Paused",
    deadline: "2026-10-01",
    ecosystem: "United Kingdom",
    highlights: [
      "Covers up to 70% of costs for micro/small companies",
      "Past rounds awarded up to £25M across a single competition",
      "Open to all sectors, from deep tech to creative industries",
    ],
  },
  {
    id: 156,
    name: "Startup SG Founder",
    organization: "Enterprise Singapore",
    logo: "https://placehold.co/100x100/EEE/999?text=S",
    description:
      "Startup SG Founder gives first-time entrepreneurs 1:1 matched startup capital and structured mentorship through Enterprise Singapore's network of Accredited Mentor Partners, to help validate and build an innovative business idea.",
    fundingAmount: "S$20,000 - S$50,000",
    category: "Government",
    tags: ["Singapore", "First-Time Founder", "Mentorship", "Seed"],
    website: "https://grants.sg/grants/startup-sg-founder",
    eligibility: [
      "Primary applicant must be a first-time founder, Singapore Citizen or PR",
      "Company must be a Singapore private limited company, under 6 months old, 51%+ local shareholding",
      "Must apply through an Accredited Mentor Partner (AMP), not directly to ESG",
      "Funding disbursed in two milestones over 12 months",
    ],
    status: "Active",
    deadline: "2026-12-01",
    ecosystem: "Singapore",
    highlights: [
      "1:1 capital matching up to S$50,000",
      "Bundled mentorship via 17+ Accredited Mentor Partners",
      "Designed specifically for first-time founders",
    ],
  },
];
