import type { Grant } from "./grantsData";

export const grantsWeb3: Grant[] = [
  {
    id: 1,
    name: "Ecosystem Support Program (ESP)",
    organization: "Ethereum Foundation",
    logo: "https://cryptologos.cc/logos/ethereum-eth-logo.svg",
    description:
      "The ESP funds open-source public goods that benefit the broader Ethereum ecosystem. It supports core protocol research, client development, developer tools, standards, testing infrastructure, and applied cryptography. In Q1 2025, the Foundation distributed over $32M across 94 projects.",
    fundingAmount: "Up to $250,000+",
    category: "Web3",
    tags: ["Ethereum", "Open Source", "Research", "Developer Tools"],
    website: "https://esp.ethereum.foundation",
    eligibility: [
      "Must build open-source public goods for the Ethereum ecosystem",
      "Focus areas: core protocol, client development, developer tools, cryptography",
      "Small grants under $30K and project grants over $30K available",
      "Academic grants and event sponsorships also offered",
    ],
    status: "Active",
    deadline: "2027-11-02",
    ecosystem: "Ethereum",
    highlights: [
      "$32M+ distributed in Q1 2025 alone",
      "Rolling applications accepted year-round",
      "Academic grants pool of $2M",
    ],
  },
  {
    id: 2,
    name: "Community Grants Program",
    organization: "Polygon Labs",
    logo: "https://cryptologos.cc/logos/polygon-matic-logo.svg",
    description:
      "The Polygon Community Treasury deploys $1 billion in POL tokens over ten years to back high-signal founders building on Polygon. The program allocates 100 million POL per year and offers multiple tracks including direct funding and consumer crypto grants.",
    fundingAmount: "100M POL/year",
    category: "Web3",
    tags: ["Polygon", "L2", "dApps", "Consumer Crypto"],
    website: "https://polygon.technology/grow",
    eligibility: [
      "Projects must be building on Polygon or willing to migrate",
      "Must demonstrate a long-term vision",
      "Open to both technical and non-technical applications",
      "Season 2 offers 35M POL via Questbook platform",
    ],
    status: "Active",
    deadline: "2027-11-07",
    ecosystem: "Polygon",
    highlights: [
      "$1 billion committed over 10 years",
      "100M POL per year allocation",
      "Technical and non-technical tracks available",
    ],
  },
  {
    id: 3,
    name: "Foundation Grants",
    organization: "Solana Foundation",
    logo: "https://cryptologos.cc/logos/solana-sol-logo.svg",
    description:
      "The Solana Foundation connects builders to funding through milestone-based grants for public goods, convertible grants for commercial projects, and direct investments. It supports open-source contributions and novel proofs of concept on Solana.",
    fundingAmount: "$200 - $10,000+",
    category: "Web3",
    tags: ["Solana", "Public Goods", "Mobile", "DeFi"],
    website: "https://solana.org/grants-funding",
    eligibility: [
      "Projects considered public goods with significant open-source contributions",
      "For-profit companies can apply for convertible grants or investments",
      "Superteam Microgrants: $200-$10,000 for early builders",
      "India-specific grants available via Superteam India ($200-$15,000)",
    ],
    status: "Active",
    deadline: "2027-11-12",
    ecosystem: "Solana",
    highlights: [
      "Fast microgrants via Superteam (decisions in 72 hours)",
      "India-specific grants through Superteam India",
      "Mobile builder grants up to $10K per team",
    ],
  },
  {
    id: 4,
    name: "Community Grant Program",
    organization: "Chainlink",
    logo: "https://cryptologos.cc/logos/chainlink-link-logo.svg",
    description:
      "Chainlink provides funding to developers, researchers, and teams to strengthen the network and accelerate adoption of connected smart contracts. It supports core tooling, data provisioning, integrations, research, and social impact initiatives.",
    fundingAmount: "$5,000 - $500,000",
    category: "Web3",
    tags: ["Chainlink", "Oracles", "Integrations", "Research"],
    website: "https://chain.link/community",
    eligibility: [
      "Must present a clear project roadmap and transparent budget",
      "Projects should show tangible progress including a working MVP",
      "Active community engagement expected",
      "Supports core tooling, integrations, and bug bounty programs",
    ],
    status: "Active",
    deadline: "2027-11-17",
    ecosystem: "Multi-chain",
    highlights: [
      "Grants up to $500K for high-impact projects",
      "Bug bounty program included",
      "Social impact initiatives welcomed",
    ],
  },
  {
    id: 5,
    name: "Foundation Grants Program",
    organization: "Uniswap Foundation",
    logo: "https://cryptologos.cc/logos/uniswap-uni-logo.svg",
    description:
      "The Uniswap Foundation allocates $30M over two years for large-scale projects across six categories. Unichain grants offer up to $7,500 for qualifying DeFi projects. A $40K Hook Incubator prize is also available.",
    fundingAmount: "$7,500 - $30M pool",
    category: "Web3",
    tags: ["Uniswap", "DeFi", "Protocol", "Governance"],
    website: "https://www.uniswapfoundation.org/grants",
    eligibility: [
      "Projects across Developers, Researchers, Governance, and Security categories",
      "Unichain grants require $250K+ TVL for DeFi projects",
      "Large-scale projects with 1-2 year execution preferred",
      "Hook Incubator for innovative AMM hooks",
    ],
    status: "Active",
    deadline: "2027-11-22",
    ecosystem: "Ethereum",
    highlights: [
      "$30M pool over two years",
      "Six distinct funding categories",
      "20M UNI annual growth budget from 2026",
    ],
  },
  {
    id: 6,
    name: "Aave Grants DAO",
    organization: "Aave",
    logo: "https://cryptologos.cc/logos/aave-aave-logo.svg",
    description:
      "Aave Grants DAO provides funding through rapid grants for smaller initiatives and community grants for larger projects. The program is funded by the Aave DAO treasury with approximately $2M per quarter.",
    fundingAmount: "$100,000 - $500,000",
    category: "Web3",
    tags: ["Aave", "DeFi", "Governance", "Lending"],
    website: "https://aavegrants.org/how-do-i-apply",
    eligibility: [
      "Projects that benefit the Aave ecosystem",
      "Rapid grants up to $100K with expedited process",
      "Community grants from $100K-$500K",
      "Larger requests (>$500K) require community governance proposals",
    ],
    status: "Active",
    deadline: "2027-11-27",
    ecosystem: "Multi-chain",
    highlights: [
      "~$2M per quarter budget",
      "Rapid grants for quick funding",
      "Rolling applications accepted",
    ],
  },
  {
    id: 7,
    name: "Retro Funding (RPGF)",
    organization: "Optimism",
    logo: "https://cryptologos.cc/logos/optimism-ethereum-op-logo.svg",
    description:
      "Optimism's signature funding mechanism operates on the principle that it's easier to agree on what was useful than what will be useful. The program allocates OP tokens retroactively to projects that have already demonstrated value.",
    fundingAmount: "16M OP per round",
    category: "Web3",
    tags: ["Optimism", "L2", "Retroactive Funding", "Public Goods"],
    website: "https://www.opgrants.io",
    eligibility: [
      "Open to projects that contributed to the Optimism/Superchain ecosystem",
      "Evaluated by badgeholders via impact metrics",
      "Transitioning from annual rounds to continuous evaluation",
      "20% of total OP supply reserved for retro funding",
    ],
    status: "Active",
    deadline: "2027-12-02",
    ecosystem: "Optimism",
    highlights: [
      "~$3 billion total allocated to public goods",
      "Continuous evaluation model from 2025",
      "One of the largest public goods funding programs",
    ],
  },
  {
    id: 8,
    name: "Foundation Grant Program",
    organization: "Arbitrum Foundation",
    logo: "https://cryptologos.cc/logos/arbitrum-arb-logo.svg",
    description:
      "Arbitrum Foundation supports builders with milestone-based funding for adoption, technical structures, and community building. Specialized programs include the $1M Trailblazer AI Grant and ArbiFuel gas sponsorship.",
    fundingAmount: "$20,000 - $150,000",
    category: "Web3",
    tags: ["Arbitrum", "L2", "AI", "Gaming"],
    website: "https://arbitrum.foundation/grants",
    eligibility: [
      "Projects currently operating with clear goals and progress milestones",
      "Funding is milestone-based (unlocked as milestones are completed)",
      "Currently accepting dApp applications",
      "$190M gaming contribution program for game developers",
    ],
    status: "Active",
    deadline: "2027-12-07",
    ecosystem: "Arbitrum",
    highlights: [
      "$1M Trailblazer AI Grant pool",
      "ArbiFuel gas fee sponsorship for early teams",
      "$190M dedicated gaming fund",
    ],
  },
  {
    id: 9,
    name: "Web3 Foundation Grants",
    organization: "Polkadot / Web3 Foundation",
    logo: "https://cryptologos.cc/logos/polkadot-new-dot-logo.svg",
    description:
      "The W3F provides strategic funding aligned with Polkadot's product-centric vision. The Decentralized Futures program distributes $20M USD and 5M DOT tokens to support new initiatives for ecosystem growth.",
    fundingAmount: "$20M + 5M DOT pool",
    category: "Web3",
    tags: ["Polkadot", "Parachain", "Core Protocol", "Interoperability"],
    website: "https://grants.web3.foundation",
    eligibility: [
      "Projects relevant to core protocol development for Polkadot",
      "Updated guidelines published in late 2025",
      "Open to individuals and teams",
      "Mechanisms include grants, investments, and service agreements",
    ],
    status: "Active",
    deadline: "2027-12-12",
    ecosystem: "Polkadot",
    highlights: [
      "$20M + 5M DOT for Decentralized Futures",
      "Transitioning to new strategic funding model",
      "Focus on JAM and core protocol",
    ],
  },
  {
    id: 11,
    name: "ATOM Accelerator DAO",
    organization: "Cosmos / Interchain Foundation",
    logo: "https://cryptologos.cc/logos/cosmos-atom-logo.svg",
    description:
      "The ATOM Accelerator DAO empowers innovators and developers to drive the future of the Cosmos Hub by providing strategic funding. The Interchain Foundation separately funds core Interchain Stack development.",
    fundingAmount: "$10,000 - $1,000,000",
    category: "Web3",
    tags: ["Cosmos", "IBC", "Interoperability", "Protocol"],
    website: "https://www.atomaccelerator.com/our-programs/grants",
    eligibility: [
      "Grant committee reviews applications focusing on impact and feasibility",
      "Successful applicants are interviewed",
      "Grant agreement includes terms, milestones, and reporting requirements",
      "ICF allocated $26.4M across five core areas in 2024",
    ],
    status: "Active",
    deadline: "2027-12-17",
    ecosystem: "Cosmos",
    highlights: [
      "Grants up to $1M for high-impact projects",
      "ICF's $26.4M core infrastructure allocation",
      "Focus on IBC and interoperability",
    ],
  },
  {
    id: 12,
    name: "Developer Grants & ProPGF",
    organization: "Filecoin Foundation",
    logo: "https://cryptologos.cc/logos/filecoin-fil-logo.svg",
    description:
      "Filecoin Foundation awards grants for projects fostering a more decentralized foundation for humanity's information. The ProPGF program runs in batches, with $4M per batch for open-source projects.",
    fundingAmount: "$5,000 - $50,000",
    category: "Web3",
    tags: ["Filecoin", "Decentralized Storage", "IPFS", "Open Source"],
    website: "https://fil.org/grants",
    eligibility: [
      "Projects must be open-source and dual-licensed (MIT and APACHE2)",
      "Teams must be self-managed",
      "ProPGF focuses on core infrastructure, SDKs, and APIs",
      "Builder Next Step Grants: $5K-$10K",
    ],
    status: "Active",
    deadline: "2027-12-22",
    ecosystem: "Filecoin",
    highlights: [
      "$4M ProPGF batches for open-source projects",
      "Spring & Fall 2026 batches planned",
      "Focus on decentralized storage infrastructure",
    ],
  },
  {
    id: 13,
    name: "Blizzard Fund",
    organization: "Avalanche Foundation",
    logo: "https://cryptologos.cc/logos/avalanche-avax-logo.svg",
    description:
      "A $200M+ fund accelerating development, growth, and innovation across the Avalanche ecosystem. Composed of contributions from Avalanche Foundation, Ava Labs, Polychain Capital, and others. Over 100 projects funded since 2021.",
    fundingAmount: "$200M+ fund",
    category: "Web3",
    tags: ["Avalanche", "Subnets", "Enterprise", "DeFi"],
    website: "https://www.blizzard.fund",
    eligibility: [
      "Open to projects building on or relevant to Avalanche ecosystem",
      "Supports equity investments, token purchases, and business development",
      "Early-stage companies (Seed and Series A) preferred",
      "Additional $290M Multiverse Incentive Program available",
    ],
    status: "Active",
    deadline: "2027-12-27",
    ecosystem: "Avalanche",
    highlights: [
      "100+ projects funded since 2021",
      "Backed by Polychain, Dragonfly, CMS Holdings",
      "$290M Multiverse Incentive Program",
    ],
  },
  {
    id: 14,
    name: "Builder Grants",
    organization: "BNB Chain",
    logo: "https://cryptologos.cc/logos/bnb-bnb-logo.svg",
    description:
      "BNB Chain offers Builder Grants up to $200K for projects developing open-source tools and public goods within the ecosystem. YZi Labs (formerly Binance Labs) additionally runs a 10-week in-person residency in Silicon Valley.",
    fundingAmount: "Up to $200,000",
    category: "Web3",
    tags: ["BNB Chain", "DeFi", "GameFi", "AI"],
    website: "https://www.bnbchain.org/en/grants",
    eligibility: [
      "Projects must be not-for-profit for BNB grants",
      "Grant size determined by application quality and feasibility",
      "Must provide long-term utility to BNB Chain ecosystem",
      "YZi Labs EASY Residence: 10-week program in Silicon Valley",
    ],
    status: "Active",
    deadline: "2028-01-01",
    ecosystem: "BNB Chain",
    highlights: [
      "Up to $200K per project",
      "Technical support and marketing assistance included",
      "YZi Labs venture-scale investments also available",
    ],
  },
  {
    id: 15,
    name: "Foundation Grants",
    organization: "Sui Foundation",
    logo: "https://cdn.prod.website-files.com/6425f546844727ce5fb9e5ab/659a55a32fcb71d65908adc3_sui-mark.svg",
    description:
      "The Sui Foundation funds developers, educators, and community members with a $50M grant initiative. Offers Developer Grants, Ecosystem Funding, RFPs, and Academic Research Awards.",
    fundingAmount: "$10,000 - $100,000",
    category: "Web3",
    tags: ["Sui", "Move Language", "Developer Tools", "Research"],
    website: "https://sui.io/request-for-proposals",
    eligibility: [
      "Open to any individual, team, or organization contributing to Sui",
      "Evaluation based on technical feasibility, innovation, and impact",
      "Academic Research Awards: fixed $25,000",
      "Potential SUI token bonuses for outstanding contributions",
    ],
    status: "Active",
    deadline: "2028-01-06",
    ecosystem: "Sui",
    highlights: [
      "$50M total allocated for ecosystem grants",
      "Academic research awards available",
      "Rolling applications with no deadlines",
    ],
  },
  {
    id: 16,
    name: "Grants Program",
    organization: "Aptos Foundation",
    logo: "https://cryptologos.cc/logos/aptos-apt-logo.svg",
    description:
      "Aptos supports original ideas that expand its ecosystem - from developer tools to applications and public goods. Includes an Ecosystem Grants track and a Payments track for wallet and payment infrastructure.",
    fundingAmount: "$5,000 - $150,000",
    category: "Web3",
    tags: ["Aptos", "Move Language", "Payments", "Public Goods"],
    website: "https://aptosnetwork.com/grants",
    eligibility: [
      "Must have a live product and demonstrate early traction",
      "Clear roadmap, milestones, and budget required",
      "Projects should be Aptos-native or open-source",
      "Google Cloud Credits up to $100K/year for recipients",
    ],
    status: "Active",
    deadline: "2028-01-11",
    ecosystem: "Aptos",
    highlights: [
      "Payments grants up to $150K",
      "Google Cloud Credits up to $100K/year for 2 years",
      "Education initiatives welcomed",
    ],
  },
  {
    id: 17,
    name: "Seed & Growth Grants",
    organization: "Starknet Foundation",
    logo: "https://www.starknet.io/wp-content/uploads/2024/01/Symbol.svg",
    description:
      "Starknet offers tiered grants: Seed Grants provide early-stage non-dilutive funding, Growth Grants support later-stage teams. A $4M Africa venture fund supports blockchain startups building on Starknet.",
    fundingAmount: "$25,000 - $1,000,000",
    category: "Web3",
    tags: ["Starknet", "ZK-Rollups", "Cairo", "L2"],
    website: "https://www.starknet.io/grants",
    eligibility: [
      "Seed Grants: must have an MVP or Proof of Concept",
      "Clear 3-month plan for fund usage required",
      "Growth Grants: must have a working product in-market",
      "Africa Fund: teams of 1-5 members, Starknet-exclusive",
    ],
    status: "Active",
    deadline: "2028-01-16",
    ecosystem: "Starknet",
    highlights: [
      "Up to $1M for growth-stage teams",
      "$4M Africa venture fund",
      "Responses within ~1 month",
    ],
  },
  {
    id: 19,
    name: "Project Catalyst",
    organization: "Cardano / IOHK",
    logo: "https://cryptologos.cc/logos/cardano-ada-logo.svg",
    description:
      "One of the world's largest decentralized grant programs, having distributed over $150M across 2,000+ funded proposals through community voting. The community proposes ideas, evaluates them, and votes on funding.",
    fundingAmount: "Up to 2,000,000 ADA",
    category: "Web3",
    tags: ["Cardano", "DAO", "Community Voting", "Decentralized"],
    website: "https://projectcatalyst.io",
    eligibility: [
      "Projects must complete all milestones within 12 months",
      "Max 6 proposals across all categories per participant",
      "Milestone-based funding with community reviewer feedback",
      "Categories: MVP, Product, Developers, Ecosystem, Partners",
    ],
    status: "Active",
    deadline: "2028-01-21",
    ecosystem: "Cardano",
    highlights: [
      "$150M+ distributed to 2,000+ projects",
      "Fully community-governed via voting",
      "Currently on Fund 15",
    ],
  },
  {
    id: 20,
    name: "HBAR Foundation Grants",
    organization: "Hedera Foundation",
    logo: "https://cryptologos.cc/logos/hedera-hbar-logo.svg",
    description:
      "The HBAR Foundation provides grants to accelerate development and adoption of the Hedera network. The Hedera Council approved an additional 7 billion HBAR grant allocation. Covers DeFi, sustainability, fintech, gaming, and education.",
    fundingAmount: "7B HBAR allocated",
    category: "Web3",
    tags: ["Hedera", "Enterprise", "Sustainability", "Fintech"],
    website: "https://hedera.foundation",
    eligibility: [
      "Open to startups, enterprises, and organizations on Hedera",
      "Grant themes: Developer Ecosystem, Community, Education, Integrations",
      "Previously launched $100M Sustainable Impact Fund",
      "$155M DeFi Development Fund available",
    ],
    status: "Active",
    deadline: "2028-01-26",
    ecosystem: "Hedera",
    highlights: [
      "7 billion HBAR multi-year allocation",
      "$100M Sustainable Impact Fund",
      "On-chain grant platform launching 2025",
    ],
  },
  {
    id: 21,
    name: "Gitcoin Grants",
    organization: "Gitcoin",
    logo: "https://cryptologos.cc/logos/gitcoin-gtc-logo.svg",
    description:
      "One of the largest public goods funding mechanisms in Web3, using Quadratic Funding to distribute matching pools. Over $4.29M distributed across 2025 OSS rounds. Community-driven with 100% of funds going to projects.",
    fundingAmount: "$4.29M+ per year",
    category: "Web3",
    tags: ["Gitcoin", "Quadratic Funding", "Open Source", "Community"],
    website: "https://grants.gitcoin.co",
    eligibility: [
      "Apply to specific rounds where eligibility criteria are met",
      "Projects checked for Sybil interference",
      "Open to any open-source or public goods project",
      "Community Rounds have $130K funding pools each",
    ],
    status: "Active",
    deadline: "2028-01-31",
    ecosystem: "Multi-chain",
    highlights: [
      "Quadratic Funding amplifies community donations",
      "100% of funds go directly to projects",
      "One of Web3's most established funding platforms",
    ],
  },
  {
    id: 23,
    name: "Developer Grant Program",
    organization: "DFINITY Foundation",
    logo: "https://cryptologos.cc/logos/internet-computer-icp-logo.svg",
    description:
      "The DFINITY program catalyzes growth of the Internet Computer ecosystem. Over 560 grants disbursed to 433+ teams totaling more than $10M. Three-tiered system for different project scales.",
    fundingAmount: "$5,000 / $25,000 / $100,000",
    category: "Web3",
    tags: ["Internet Computer", "ICP", "Canisters", "Web3"],
    website: "https://dfinity.org/grants",
    eligibility: [
      "Open to developers and teams building on Internet Computer",
      "Three tiers: $5K, $25K, and $100K",
      "$100K tier generally follows a smaller initial grant",
      "Applications reviewed on rolling basis",
    ],
    status: "Active",
    deadline: "2028-02-05",
    ecosystem: "Internet Computer",
    highlights: [
      "560+ grants to 433+ teams",
      "$223M made available historically",
      "Developer tooling and integrations prioritized",
    ],
  },
  {
    id: 24,
    name: "Ecosystem Grants",
    organization: "Tezos Foundation",
    logo: "https://cryptologos.cc/logos/tezos-xtz-logo.svg",
    description:
      "The Tezos Foundation funds non-profit, commons-enhancing projects addressing ecosystem needs. 43 initiatives totaling $9.81M approved in a recent biannual period. Covers baking, developer experience, education, privacy, and security.",
    fundingAmount: "Up to $50,000 (small grants)",
    category: "Web3",
    tags: ["Tezos", "Formal Verification", "Privacy", "Education"],
    website: "https://grants.tezos.foundation",
    eligibility: [
      "Anyone with an idea that boosts Tezos ecosystem development",
      "Primarily given to non-profit, commons-enhancing projects",
      "Submissions accepted quarterly",
      "~4 weeks review + ~4 weeks paperwork",
    ],
    status: "Active",
    deadline: "2028-02-10",
    ecosystem: "Tezos",
    highlights: [
      "$9.81M approved in recent biannual period",
      "Quarterly review cycles",
      "Focus on formal verification and privacy",
    ],
  },
  {
    id: 25,
    name: "Base Ecosystem Fund",
    organization: "Coinbase / Base",
    logo: "https://avatars.githubusercontent.com/u/108554348",
    description:
      "The Base Ecosystem Fund invests in next-gen onchain projects. Base Batches is an 8-week virtual accelerator. Fast retroactive grants of 1-5 ETH are available for already-shipped projects building on Base.",
    fundingAmount: "$10K - $50K + 1-5 ETH retro",
    category: "Web3",
    tags: ["Base", "L2", "Coinbase", "Onchain"],
    website: "https://docs.base.org/get-started/get-funded",
    eligibility: [
      "Early-stage (pre-seed to seed) projects building on Base",
      "Base Batches: pre-product teams with less than ~$250K raised",
      "Retroactive grants require a live MVP on Base",
      "8-week virtual accelerator with Demo Day in SF",
    ],
    status: "Active",
    deadline: "2028-02-15",
    ecosystem: "Base",
    highlights: [
      "1-5 ETH retroactive grants for shipped projects",
      "8-week Base Batches accelerator",
      "$50K investment for top performing teams",
    ],
  },
  {
    id: 26,
    name: "xGov Grants & Accelerator",
    organization: "Algorand Foundation",
    logo: "https://cryptologos.cc/logos/algorand-algo-logo.svg",
    description:
      "Algorand's fully community-driven xGov system allows a community-elected council to review all grant proposals. The Accelerator provides up to $50K in initial funding. India-specific Startup Lab offers infrastructure resources.",
    fundingAmount: "Up to $50,000",
    category: "Web3",
    tags: ["Algorand", "xGov", "Startups", "India"],
    website: "https://algorand.co/entrepreneurs/startup-programs",
    eligibility: [
      "Accelerator: early-stage startups with Algorand-based applications",
      "Established startups on other blockchains with migration plans accepted",
      "xGov: community-driven proposal review",
      "India Startup Lab: must have MVP or working prototype",
    ],
    status: "Active",
    deadline: "2028-02-20",
    ecosystem: "Algorand",
    highlights: [
      "Community-governed xGov system",
      "India-specific Startup Lab",
      "Rolling applications for Accelerator",
    ],
  },
  {
    id: 27,
    name: "Compound Foundation Grants",
    organization: "Compound DAO",
    logo: "https://cryptologos.cc/logos/compound-comp-logo.svg",
    description:
      "The Compound Grants Program provides funding for projects benefiting the Compound protocol. In 2025, ~$9M in COMP was transferred to fund an 18-month Compound Foundation, plus ~$8.42M DAI for protocol operations.",
    fundingAmount: "~$9M pool (18 months)",
    category: "Web3",
    tags: ["Compound", "DeFi", "Lending", "Governance"],
    website: "https://compound.finance",
    eligibility: [
      "Projects that benefit the Compound ecosystem",
      "Overseen by a grants committee",
      "Proposals voted on by COMP token holders",
      "Foundation established June 2025 with 18-month term",
    ],
    status: "Active",
    deadline: "2028-02-25",
    ecosystem: "Ethereum",
    highlights: [
      "~$9M COMP for 18-month foundation",
      "~$8.42M DAI for protocol operations",
      "Committee-reviewed applications",
    ],
  },
  {
    id: 28,
    name: "LEGO Grants",
    organization: "Lido DAO",
    logo: "https://cryptologos.cc/logos/lido-dao-ldo-logo.svg",
    description:
      "LEGO (Lido Ecosystem Grants Organization) funds individuals, projects, and initiatives benefiting Lido. Grants are categorized as sandgrains, pebbles, boulders, and mountains by size. 2026 budget proposed at $60M.",
    fundingAmount: "15,000 LDO/quarter",
    category: "Web3",
    tags: ["Lido", "Liquid Staking", "Ethereum", "DAO"],
    website: "https://lido.fi/lego",
    eligibility: [
      "Open to developers and community members",
      "Plans to improve the Lido ecosystem required",
      "8-member LEGO Council reviews proposals",
      "Each member responsible for a specific Lido segment",
    ],
    status: "Active",
    deadline: "2028-03-01",
    ecosystem: "Ethereum",
    highlights: [
      "$60M proposed 2026 budget",
      "Tiered system: sandgrains to mountains",
      "Expanding beyond liquid staking",
    ],
  },
  {
    id: 29,
    name: "Community Grants",
    organization: "MakerDAO / Sky Protocol",
    logo: "https://cryptologos.cc/logos/maker-mkr-logo.svg",
    description:
      "MakerDAO (now Sky Protocol) funds projects that increase DAI/USDS adoption, support emerging economies, and open new markets. Milestone-based distribution ensures accountability.",
    fundingAmount: "5,000 - 50,000 DAI",
    category: "Web3",
    tags: ["MakerDAO", "Stablecoin", "DAI", "Financial Inclusion"],
    website: "https://vote.makerdao.com",
    eligibility: [
      "Must increase DAI/USDS adoption or support emerging economies",
      "Novel uses for the stablecoin that further Foundation principles",
      "Milestone-based fund distribution",
      "Open to projects globally",
    ],
    status: "Active",
    deadline: "2028-03-06",
    ecosystem: "Ethereum",
    highlights: [
      "Focus on financial inclusion",
      "Milestone-based payouts",
      "Rebranded to Sky Protocol (MKR->SKY, DAI->USDS)",
    ],
  },
  {
    id: 30,
    name: "WAGBI Developer Grants",
    organization: "Alchemy",
    logo: "https://www.alchemy.com/best/cdn-cgi/image/width=256,height=256/https://static.alchemyapi.io/images/marketing/alchemy-logo.png",
    description:
      "A $25M grant initiative supporting community developers building Web3 projects. Each project can receive up to $50K in Alchemy platform credits for building DeFi protocols, NFT marketplaces, or any Web3 project.",
    fundingAmount: "Up to $50,000 (credits)",
    category: "Web3",
    tags: ["Alchemy", "Developer Platform", "API", "Beginner Friendly"],
    website: "https://www.alchemy.com/developer-grant-program",
    eligibility: [
      "Developers starting in Web3 who are ready to build",
      "Must have a live website",
      "Agree to add Alchemy Certified Infrastructure badge",
      "Commit to at least 1 co-marketing initiative annually",
    ],
    status: "Active",
    deadline: "2028-03-11",
    ecosystem: "Multi-chain",
    highlights: [
      "$25M total pool",
      "Great for beginners entering Web3",
      "Platform credits for compute and APIs",
    ],
  },
  {
    id: 31,
    name: "MetaMask Grants DAO",
    organization: "ConsenSys",
    logo: "https://upload.wikimedia.org/wikipedia/commons/3/36/MetaMask_Fox.svg",
    description:
      "An employee-led DAO issuing grants to developers worldwide, funded at $2.4M per year. It funds open-source projects adding value to the MetaMask ecosystem including wallet extensions, Snaps, and decentralized identity.",
    fundingAmount: "$2.4M/year total",
    category: "Web3",
    tags: ["MetaMask", "Wallet", "Snaps", "ConsenSys"],
    website: "https://metamaskgrants.org",
    eligibility: [
      "Open to any developer building impactful, open-source Web3 experiences",
      "Must add value to the MetaMask ecosystem",
      "Two tracks: Leadership Committee Grants and DAO-wide voted grants",
      "ConsenSys Fellowship: 12-week pre-accelerator also available",
    ],
    status: "Active",
    deadline: "2028-03-16",
    ecosystem: "Ethereum",
    highlights: [
      "$600K per quarter budget",
      "MetaMask Snaps ecosystem growing rapidly",
      "Fellowship program with up to $1.5M follow-on",
    ],
  },
  {
    id: 32,
    name: "XRPL Grants",
    organization: "Ripple / XRPL Foundation",
    logo: "https://cryptologos.cc/logos/xrp-xrp-logo.svg",
    description:
      "Funds software development projects leveraging the XRP Ledger. Since 2021, over 140 projects from 28 countries have received grants covering sustainability, digital identity, game-fi, and financial solutions.",
    fundingAmount: "$10,000 - $200,000",
    category: "Web3",
    tags: ["XRPL", "Ripple", "Payments", "Identity"],
    website: "https://xrplgrants.org",
    eligibility: [
      "Open to developers and teams building on XRP Ledger",
      "Projects must leverage XRPL technology",
      "Rolling applications (previously wave-based)",
      "New programming expected Spring 2026",
    ],
    status: "Paused",
    deadline: "2028-03-21",
    ecosystem: "XRPL",
    highlights: [
      "140+ projects funded from 28 countries",
      "XRPL Accelerator 2025 with Tenity",
      "New program launching Spring 2026",
    ],
  },
  {
    id: 33,
    name: "Stellar Community Fund",
    organization: "Stellar Development Foundation",
    logo: "https://cryptologos.cc/logos/stellar-xlm-logo.svg",
    description:
      "An open-application program distributing awards based on community input for projects on Stellar and Soroban. Also offers an Enterprise Fund for venture investments and bug bounties up to $250K.",
    fundingAmount: "Up to $150,000 in XLM",
    category: "Web3",
    tags: ["Stellar", "Soroban", "Cross-border", "Fintech"],
    website: "https://communityfund.stellar.org",
    eligibility: [
      "Open to developers building on Stellar/Soroban",
      "Community-driven award distribution",
      "Enterprise Fund supports all stages up to Series E",
      "Academic research grants for financial inclusion studies",
    ],
    status: "Active",
    deadline: "2028-03-26",
    ecosystem: "Stellar",
    highlights: [
      "Up to $150K per project",
      "Bug bounties up to $250K",
      "Enterprise Fund for venture investments",
    ],
  },
  {
    id: 36,
    name: "Grants Program",
    organization: "The Graph Foundation",
    logo: "https://cryptologos.cc/logos/the-graph-grt-logo.svg",
    description:
      "Funds protocol development, tooling, dApp development, and growth initiatives. Over $5M allocated in Wave 1. Community grants managed by Graph AdvocatesDAO support smaller contributions up to $20K.",
    fundingAmount: "Up to $20,000 (community)",
    category: "Web3",
    tags: ["The Graph", "Indexing", "APIs", "Data"],
    website: "https://thegraph.com/grants",
    eligibility: [
      "Open to individuals and projects contributing to The Graph",
      "Open-source contributions preferred",
      "Technical skills not required for all grant types",
      "Evolving toward multi-service data and AI infrastructure",
    ],
    status: "Active",
    deadline: "2028-03-31",
    ecosystem: "Multi-chain",
    highlights: [
      "$5M+ distributed in Wave 1",
      "AdvocatesDAO community grants",
      "Growing AI and data services focus",
    ],
  },
  {
    id: 37,
    name: "OceanDAO & Shipyard",
    organization: "Ocean Protocol",
    logo: "https://cryptologos.cc/logos/ocean-protocol-ocean-logo.svg",
    description:
      "Two programs: OceanDAO distributes 180M OCEAN ($140M) for community-curated grants. Ocean Shipyard provides $30K-$75K grants for 3-6 month projects plus technical assistance and marketing support.",
    fundingAmount: "$30,000 - $75,000",
    category: "Web3",
    tags: ["Ocean", "Data Economy", "AI", "Data Markets"],
    website: "https://oceanprotocol.com/build/shipyard",
    eligibility: [
      "Must use Ocean technology and/or OCEAN token",
      "Projects must be open source with experienced teams",
      "Working code and clear use case required",
      "OceanDAO: up to $50K per grant in monthly rounds",
    ],
    status: "Active",
    deadline: "2028-04-05",
    ecosystem: "Multi-chain",
    highlights: [
      "$140M total OceanDAO pool",
      "Shipyard grants: $30K-$75K with support",
      "Focus on data economy and AI",
    ],
  },
  {
    id: 38,
    name: "Community Grants",
    organization: "Celo Foundation",
    logo: "https://cryptologos.cc/logos/celo-celo-logo.svg",
    description:
      "The Celo Foundation supports projects committed to building a financial system creating conditions for prosperity for all. Offers retroactive funding, grants, and sustainable revenue models. GoodBuilders Program offers year-long mentorship.",
    fundingAmount: "Varies by program",
    category: "Web3",
    tags: ["Celo", "Financial Inclusion", "Mobile-First", "ReFi"],
    website: "https://docs.celo.org/build-on-celo/fund-your-project",
    eligibility: [
      "Projects must align with Celo's mission of financial inclusion",
      "Include Karma GAP project profile when applying",
      "Open to builders at different stages",
      "GoodBuilders: year-long support with funding and mentorship",
    ],
    status: "Active",
    deadline: "2028-04-10",
    ecosystem: "Celo",
    highlights: [
      "Strong financial inclusion focus",
      "GoodBuilders year-long program",
      "Retroactive and proactive funding available",
    ],
  },
  {
    id: 39,
    name: "DAO Grants",
    organization: "Decentraland",
    logo: "https://cryptologos.cc/logos/decentraland-mana-logo.svg",
    description:
      "Community-governed grants across eight categories including Core Unit, Platform, In-world Building, and Community Experiences. DAO holds 222M MANA on a 10-year vesting schedule. Proposals voted on over 7-day windows.",
    fundingAmount: "Up to $240,000",
    category: "Web3",
    tags: ["Decentraland", "Metaverse", "Virtual Worlds", "DAO"],
    website: "https://decentraland.org/dao/grants",
    eligibility: [
      "Anyone can submit a grant proposal via DAO portal",
      "Must provide Ethereum address, project description, and implementation plan",
      "Lower tier: up to $20K; Higher tier: $20K-$240K",
      "Paid in MANA at current exchange rate",
    ],
    status: "Active",
    deadline: "2028-04-15",
    ecosystem: "Decentraland",
    highlights: [
      "222M MANA DAO treasury",
      "Eight distinct grant categories",
      "Fully community-governed voting",
    ],
  },
  {
    id: 40,
    name: "Game Maker Fund & DAO",
    organization: "The Sandbox",
    logo: "https://cryptologos.cc/logos/the-sandbox-sand-logo.svg",
    description:
      "Game Maker Fund offers $5K-$30K per game for content creation. DAO distributed 200K USDC across 38 grants in 20 countries. Open Metaverse Accelerator (with Brinc) provides $50M for 100 startups.",
    fundingAmount: "$5,000 - $250,000",
    category: "Web3",
    tags: ["Sandbox", "Metaverse", "Game Making", "Creator Economy"],
    website: "https://www.sandbox.game",
    eligibility: [
      "Must pass KYC and be over 18",
      "Regular Game Maker user in good standing",
      "Comply with Sandbox Terms & Conditions",
      "Accelerator: up to $250K investment + $150K in SAND tokens",
    ],
    status: "Active",
    deadline: "2028-04-20",
    ecosystem: "The Sandbox",
    highlights: [
      "$50M accelerator for 100 startups",
      "38 grants across 20 countries",
      "Judged on quality, originality, and playability",
    ],
  },
  {
    id: 41,
    name: "Ecosystem Working Group Grants",
    organization: "ENS DAO",
    logo: "https://cryptologos.cc/logos/ethereum-name-service-ens-logo.svg",
    description:
      "The ENS Ecosystem Working Group funds builders of ENS-specific or ENS-centric projects. Budget of 836K USDC through April 2025. Also sponsors Gitcoin Grants rounds ($50K) and Growth Grants ($10K retroactive awards).",
    fundingAmount: "$10,000 - $836,000 budget",
    category: "Web3",
    tags: ["ENS", "Domain Names", "Identity", "Ethereum"],
    website: "https://basics.ensdao.org/ens-ecosystem-wg",
    eligibility: [
      "Projects must be ENS-specific or ENS-centric",
      "Projects that would struggle getting grants from other DAOs due to ENS focus",
      "Contact stewards or join weekly working group calls",
      "Growth Grants: $10K retroactive awards to 5 projects per round",
    ],
    status: "Active",
    deadline: "2028-04-25",
    ecosystem: "Ethereum",
    highlights: [
      "Funded by .eth domain registration fees",
      "$50K Gitcoin Grants sponsorships",
      "Weekly working group calls for coordination",
    ],
  },
  {
    id: 42,
    name: "Zcash Community Grants",
    organization: "Zcash / Financial Privacy Foundation",
    logo: "https://cryptologos.cc/logos/zcash-zec-logo.svg",
    description:
      "Funds independent teams for major development and public-good work in the Zcash ecosystem. Funded by 8% of mining rewards through November 2028. Coinholder-Directed Retroactive Grants Program for community voting.",
    fundingAmount: "8% of block rewards",
    category: "Web3",
    tags: ["Zcash", "Privacy", "Zero-Knowledge", "Mining"],
    website: "https://zcashcommunitygrants.org",
    eligibility: [
      "Open to independent teams entering the Zcash ecosystem",
      "Applications accepted on rolling basis",
      "Reviewed every other week by 5-person elected committee",
      "Retroactive grants require proposal during open call periods",
    ],
    status: "Active",
    deadline: "2028-04-30",
    ecosystem: "Zcash",
    highlights: [
      "Continuous funding from mining rewards",
      "Funded through November 2028",
      "Privacy-first development",
    ],
  },
  {
    id: 43,
    name: "1inch Grants Program",
    organization: "1inch Foundation",
    logo: "https://cryptologos.cc/logos/1inch-1inch-logo.svg",
    description:
      "A $3M grants program targeting DeFi developers across network development, community development, and research & analytics. Funds aggregation products, AMMs, wallets, L2 protocols, educational materials, and data analytics.",
    fundingAmount: "$3M total pool",
    category: "Web3",
    tags: ["1inch", "DEX Aggregator", "DeFi", "Research"],
    website: "https://1inch.io/foundation",
    eligibility: [
      "Projects recently started in DeFi with no prior funding",
      "Developers, teams, or individuals benefiting the 1inch ecosystem",
      "Must comply with regulatory restrictions",
      "Grants paid in 1INCH tokens or other agreed currencies",
    ],
    status: "Active",
    deadline: "2028-05-05",
    ecosystem: "Multi-chain",
    highlights: [
      "$3M over 12 months",
      "Great for first-time funded projects",
      "Three categories: network, community, research",
    ],
  },
  {
    id: 44,
    name: "Radicle Grants",
    organization: "Radworks",
    logo: "https://app.radworks.org/favicon.ico",
    description:
      "A $1M grants program funding contributions that improve the Radicle ecosystem for decentralized, open-source collaboration. Seed Grants up to $50K for small contributions; Tree Grants up to $500K for larger projects.",
    fundingAmount: "$50,000 - $500,000",
    category: "Web3",
    tags: ["Radicle", "Open Source", "Git", "Decentralized"],
    website: "https://github.com/radicle-dev/radicle-grants",
    eligibility: [
      "Individuals or small teams for Seed Grants (up to $50K)",
      "Larger teams or companies for Tree Grants ($50K-$500K)",
      "Must contribute to the Radicle ecosystem",
      "Payment: 40% upfront, 60% upon completion",
    ],
    status: "Active",
    deadline: "2028-05-10",
    ecosystem: "Multi-chain",
    highlights: [
      "Up to $500K for Tree Grants",
      "40% upfront payment structure",
      "Focus on decentralized collaboration",
    ],
  },
  {
    id: 45,
    name: "Navigators & Core Grants",
    organization: "Mina Foundation",
    logo: "https://cryptologos.cc/logos/mina-protocol-mina-logo.svg",
    description:
      "Multiple grant tracks: Navigators (Season 3) distributes 2.3M MINA for zkApp development. Core Grants fund public goods infrastructure via RFPs. Builders Grants support solving real-world problems with Mina.",
    fundingAmount: "Up to 100,000 MINA",
    category: "Web3",
    tags: ["Mina", "ZK-SNARKs", "zkApps", "Lightweight"],
    website: "https://minaprotocol.com/grants-wip",
    eligibility: [
      "Open to developers, founders, designers, marketers",
      "Building infrastructure for zkApp developers",
      "Navigators Starter Track: up to 15K MINA",
      "Navigators Growth Track: up to 100K MINA",
    ],
    status: "Active",
    deadline: "2028-05-15",
    ecosystem: "Mina",
    highlights: [
      "2.3M MINA for Season 3 Navigators",
      "Focus on zero-knowledge applications",
      "Lightest blockchain by design",
    ],
  },
  {
    id: 46,
    name: "Sonic Innovator Fund",
    organization: "Fantom / Sonic Foundation",
    logo: "https://cryptologos.cc/logos/fantom-ftm-logo.svg",
    description:
      "Up to 200M FTM (~$120M) to help developers migrate to Sonic technology. Sonic Labs accelerator mentored by Andre Cronje. Additional 335M FTM incentive program with Gitcoin Grants.",
    fundingAmount: "~$120M total fund",
    category: "Web3",
    tags: ["Fantom", "Sonic", "DeFi", "High Performance"],
    website: "https://blog.fantom.foundation/how-to-get-funding-on-fantom",
    eligibility: [
      "Developers creating applications using Fantom/Sonic technology",
      "Criteria: vision, tech stack utilization, user base, uniqueness",
      "Priority for existing Fantom apps for migration grants",
      "Accelerator: up to 5 projects from 1M FTM pool",
    ],
    status: "Active",
    deadline: "2028-05-20",
    ecosystem: "Fantom",
    highlights: [
      "200M FTM Innovator Fund",
      "Mentored by Andre Cronje",
      "335M FTM Gitcoin incentive program",
    ],
  },
  {
    id: 47,
    name: "Foundation Grants",
    organization: "Moonbeam Foundation",
    logo: "https://moonbeam.network/wp-content/uploads/2020/03/cropped-Moonbeam-Favicon-550px-32x32.png",
    description:
      "Financial support, technical assistance, co-marketing, mentorship, and strategic guidance for startups in the Moonbeam ecosystem. Three tiers from under $50K to $3M for mature projects.",
    fundingAmount: "Up to $3,000,000",
    category: "Web3",
    tags: ["Moonbeam", "Polkadot", "EVM", "Cross-Chain"],
    website: "https://moonbeam.network/build/grants",
    eligibility: [
      "Open to projects building in the Moonbeam ecosystem",
      "Three tiers: up to $50K, $50K-$150K, $150K-$3M",
      "Managed by 2 Foundation + 3 community-elected members",
      "No gambling, illicit trade, or criminal activity projects",
    ],
    status: "Active",
    deadline: "2028-05-25",
    ecosystem: "Moonbeam",
    highlights: [
      "Up to $3M for mature ecosystem projects",
      "Community-elected grant committee",
      "EVM-compatible on Polkadot",
    ],
  },
  {
    id: 49,
    name: "Kadena Grants",
    organization: "Kadena",
    logo: "https://cryptologos.cc/logos/kadena-kda-logo.svg",
    description:
      "A $50M grant initiative with dual focus: $25M toward real-world asset (RWA) tokenization and $25M toward EVM and AI-driven innovation. Strong focus on Chainweb EVM tooling.",
    fundingAmount: "$50M total",
    category: "Web3",
    tags: ["Kadena", "RWA", "AI", "Chainweb"],
    website: "https://kadena.io",
    eligibility: [
      "Developers building within Kadena ecosystem",
      "Focus on Chainweb EVM tooling",
      "RWA tokenization projects (real estate, debt instruments)",
      "AI-integrated blockchain applications",
    ],
    status: "Active",
    deadline: "2028-05-30",
    ecosystem: "Kadena",
    highlights: [
      "$25M for RWA tokenization",
      "$25M for EVM and AI innovation",
      "Launched in 2025",
    ],
  },
  {
    id: 50,
    name: "Harmony Grants",
    organization: "Harmony Foundation",
    logo: "https://cryptologos.cc/logos/harmony-one-logo.svg",
    description:
      "Harmony established a $300M+ treasury fund for grants, DAOs, bounties, and investments. Structured as 6-week programs focused on driving mainnet utility, decentralized community building, and cryptographic innovations.",
    fundingAmount: "$50,000 - $250,000",
    category: "Web3",
    tags: ["Harmony", "Cross-Border", "Privacy", "Sharding"],
    website: "https://open.harmony.one/300m-on-bounties-grants-daos",
    eligibility: [
      "Must bring active users with high 7-day retention",
      "Bringing assets, transactions, and volume to Harmony Mainnet",
      "Milestone-based payouts of $10K increments",
      "Currently not accepting new applications",
    ],
    status: "Paused",
    deadline: "2028-06-04",
    ecosystem: "Harmony",
    highlights: [
      "$300M+ original treasury",
      "Focus on cross-border finance",
      "Currently paused - check back for updates",
    ],
  },
];
