import type { Grant } from "./grantsData";

export const grantsAiDeepTech: Grant[] = [
  {
    id: 121,
    name: "Google Research Scholar Program",
    organization: "Google",
    logo: "https://placehold.co/100x100/EEE/999?text=G",
    description:
      "The Google Research Scholar Program supports early-career professors pursuing research in CS, engineering, and related fields. Awards provide unrestricted funding for research in AI, ML, systems, HCI, and quantum computing.",
    fundingAmount: "$60,000",
    category: "AI & Deep Tech",
    tags: ["Google", "AI", "Academic Research", "Machine Learning"],
    website: "https://research.google/outreach/research-scholar-program",
    eligibility: [
      "Tenure-track professors within 5 years of starting their appointment",
      "Must be at an accredited university worldwide",
      "Research in CS, AI, ML, systems, security, or related fields",
      "Annual call with October deadline",
    ],
    status: "Active",
    deadline: "2026-05-30",
    ecosystem: "USA",
    highlights: [
      "Unrestricted gift funding - use it for anything research-related",
      "150+ scholars funded globally each year",
      "Opportunity for ongoing Google collaboration",
    ],
  },
  {
    id: 122,
    name: "Microsoft Research Grants",
    organization: "Microsoft",
    logo: "https://placehold.co/100x100/EEE/999?text=M",
    description:
      "Microsoft Research provides grants and fellowships to support academic research in AI, systems, and computing. Programs include the Microsoft Investigator Fellowship, Ada Lovelace Fellowship, and targeted RFPs across research areas.",
    fundingAmount: "Up to $200,000",
    category: "AI & Deep Tech",
    tags: ["Microsoft", "AI", "Research", "Fellowship"],
    website: "https://www.microsoft.com/en-us/research/academic-programs",
    eligibility: [
      "Academic researchers at accredited universities",
      "PhD students eligible for fellowship programs",
      "Must align with Microsoft Research's focus areas",
      "Proposals reviewed by Microsoft Research scientists",
    ],
    status: "Active",
    deadline: "2026-05-29",
    ecosystem: "USA",
    highlights: [
      "Access to Azure compute credits for research",
      "Collaboration opportunities with MSR scientists",
      "Fellowship includes stipend + conference travel",
    ],
  },
  {
    id: 123,
    name: "NVIDIA Academic Hardware Grant",
    organization: "NVIDIA",
    logo: "https://placehold.co/100x100/EEE/999?text=N",
    description:
      "NVIDIA's Academic Hardware Grant donates GPUs to researchers working on deep learning, autonomous systems, robotics, and scientific computing. It enables academic labs to access cutting-edge GPU hardware for research.",
    fundingAmount: "GPU hardware grants",
    category: "AI & Deep Tech",
    tags: ["NVIDIA", "GPU", "Deep Learning", "Hardware"],
    website: "https://www.nvidia.com/en-us/industries/higher-education-research/academic-grant-program/",
    eligibility: [
      "Faculty and researchers at accredited universities",
      "Research must involve GPU computing (deep learning, HPC, graphics)",
      "Must publish results and acknowledge NVIDIA support",
      "Applications accepted on a rolling basis",
    ],
    status: "Active",
    deadline: "2026-09-13",
    ecosystem: "USA",
    highlights: [
      "Free GPU hardware for academic research",
      "Access to NVIDIA's DGX and A100/H100 systems",
      "Supports research in AI, autonomous systems, and HPC",
    ],
  },
  {
    id: 124,
    name: "Meta Research Awards",
    organization: "Meta",
    logo: "https://placehold.co/100x100/EEE/999?text=M",
    description:
      "Meta Research funds academic work across AI, VR/AR, privacy, integrity, and social computing. Awards support specific RFP topics and provide unrestricted funding for 1-2 year research projects.",
    fundingAmount: "Up to $100,000",
    category: "AI & Deep Tech",
    tags: ["Meta", "AI", "VR/AR", "Privacy", "Research"],
    website: "https://research.facebook.com/research-awards",
    eligibility: [
      "Faculty at accredited universities worldwide",
      "Must respond to specific RFP topic areas",
      "PhD students eligible as PI in some programs",
      "Multiple RFPs released throughout the year",
    ],
    status: "Active",
    deadline: "2026-09-18",
    ecosystem: "USA",
    highlights: [
      "Unrestricted gift funding",
      "Topics span AI, VR/AR, privacy, and systems",
      "Opportunity for internship placements at Meta",
    ],
  },
  {
    id: 125,
    name: "Amazon Science Research Awards",
    organization: "Amazon",
    logo: "https://placehold.co/100x100/EEE/999?text=A",
    description:
      "Amazon Science Research Awards fund academic research in ML, robotics, NLP, computer vision, and cloud computing. Awards include cash funding plus AWS credits to support computationally intensive research.",
    fundingAmount: "Up to $80,000 + AWS credits",
    category: "AI & Deep Tech",
    tags: ["Amazon", "ML", "Robotics", "AWS", "Research"],
    website: "https://www.amazon.science/research-awards",
    eligibility: [
      "Faculty at accredited universities",
      "Research in ML, NLP, robotics, computer vision, or related fields",
      "Must propose a 1-year research project",
      "Annual open call with multiple topic areas",
    ],
    status: "Active",
    deadline: "2026-09-23",
    ecosystem: "USA",
    highlights: [
      "Cash award plus significant AWS credits",
      "Access to Amazon scientists for collaboration",
      "Topics aligned with Amazon's research priorities",
    ],
  },
  {
    id: 126,
    name: "OpenAI Researcher Access Program",
    organization: "OpenAI",
    logo: "https://placehold.co/100x100/EEE/999?text=O",
    description:
      "OpenAI provides API credits and research funding to academics studying AI safety, alignment, fairness, and capabilities. The program supports research that advances understanding of large language models and AI systems.",
    fundingAmount: "API credits + funding",
    category: "AI & Deep Tech",
    tags: ["OpenAI", "AI Safety", "LLM", "Research"],
    website: "https://openai.com/research",
    eligibility: [
      "Academic researchers studying AI safety, alignment, or capabilities",
      "Must propose research that uses OpenAI's models or advances AI safety",
      "Graduate students and faculty eligible",
      "Rolling applications",
    ],
    status: "Active",
    deadline: "2026-09-28",
    ecosystem: "USA",
    highlights: [
      "Free API access for approved research",
      "Focus on AI safety and alignment research",
      "Potential for collaboration with OpenAI researchers",
    ],
  },
  {
    id: 127,
    name: "AI2 Grants (Allen Institute for AI)",
    organization: "Allen Institute for AI",
    logo: "https://placehold.co/100x100/EEE/999?text=A",
    description:
      "AI2 funds impactful AI research through grants, fellowships, and partnerships. Founded by Paul Allen, it focuses on AI for the common good - supporting NLP, computer vision, and AI for science research.",
    fundingAmount: "Up to $500,000",
    category: "AI & Deep Tech",
    tags: ["AI2", "NLP", "AI for Good", "Research"],
    website: "https://allenai.org",
    eligibility: [
      "Academic researchers and nonprofits",
      "Research must advance AI for the common good",
      "Focus on NLP, knowledge representation, and AI for science",
      "Collaborative projects with AI2 researchers preferred",
    ],
    status: "Active",
    deadline: "2026-10-03",
    ecosystem: "USA",
    highlights: [
      "Founded by Paul Allen with $125M+ investment",
      "Producers of Semantic Scholar, AllenNLP, OLMo",
      "Open-source first approach to AI research",
    ],
  },
  {
    id: 128,
    name: "Samsung AI Research Fund",
    organization: "Samsung",
    logo: "https://placehold.co/100x100/EEE/999?text=S",
    description:
      "Samsung's Global Research Outreach program funds academic research in AI, 5G/6G, semiconductor, and next-gen computing. Selected professors receive funding and work closely with Samsung Research scientists.",
    fundingAmount: "Up to $100,000",
    category: "AI & Deep Tech",
    tags: ["Samsung", "AI", "5G", "Semiconductor", "Research"],
    website: "https://research.samsung.com/gro",
    eligibility: [
      "University professors and research scientists worldwide",
      "Research must align with Samsung's technology focus areas",
      "Proposals for 1-year projects with clear deliverables",
      "Annual call with specific topic announcements",
    ],
    status: "Active",
    deadline: "2026-10-08",
    ecosystem: "Global",
    highlights: [
      "Collaboration with Samsung Research labs globally",
      "Topics span AI, 5G/6G, materials science, and HCI",
      "Potential for multi-year renewal",
    ],
  },
  {
    id: 129,
    name: "Huawei Spark Program",
    organization: "Huawei",
    logo: "https://placehold.co/100x100/EEE/999?text=H",
    description:
      "Huawei's Spark Program funds collaborative research with universities in AI, networking, cloud computing, and wireless technology. It provides grants and access to Huawei's R&D infrastructure for joint research.",
    fundingAmount: "Up to $50,000",
    category: "AI & Deep Tech",
    tags: ["Huawei", "5G", "Cloud", "AI", "Research"],
    website: "https://www.huawei.com/minisite/seeds-for-the-future/index.html",
    eligibility: [
      "University researchers and PhD students",
      "Research in ICT, AI, cloud, or wireless technologies",
      "Joint research projects with Huawei R&D teams",
      "Multiple programs for different career stages",
    ],
    status: "Active",
    deadline: "2026-10-13",
    ecosystem: "Global",
    highlights: [
      "Joint research with Huawei's 15 R&D centers",
      "Access to Huawei cloud and compute infrastructure",
      "Seeds for the Future program for students",
    ],
  },
  {
    id: 130,
    name: "Intel oneAPI Innovation Program",
    organization: "Intel",
    logo: "https://placehold.co/100x100/EEE/999?text=I",
    description:
      "Intel's oneAPI Academic Center of Excellence and Innovation programs support researchers and developers building with Intel's oneAPI toolkit. Grants fund research in heterogeneous computing, AI acceleration, and HPC.",
    fundingAmount: "Up to $50,000",
    category: "AI & Deep Tech",
    tags: ["Intel", "HPC", "Heterogeneous Computing", "oneAPI"],
    website: "https://www.intel.com/content/www/us/en/developer/tools/oneapi/training/academic-program.html",
    eligibility: [
      "Faculty and researchers at accredited universities",
      "Research involving Intel architectures and oneAPI",
      "Must produce educational materials or research publications",
      "Hardware donation programs also available",
    ],
    status: "Active",
    deadline: "2026-10-18",
    ecosystem: "USA",
    highlights: [
      "Access to Intel DevCloud for testing and development",
      "Hardware donation for research labs",
      "oneAPI training and curriculum support",
    ],
  },
];
