import type { Grant } from "./grantsData";

export const grantsUniversity: Grant[] = [
  {
    id: 91,
    name: "MIT Solve",
    organization: "MIT",
    logo: "https://placehold.co/100x100/EEE/999?text=M",
    description:
      "MIT Solve is a marketplace for social impact innovation. It runs annual challenges in health, learning, economic prosperity, and sustainability. Solver teams receive funding, mentorship, and access to MIT's network.",
    fundingAmount: "Up to $200,000",
    category: "University",
    tags: ["MIT", "Social Impact", "Innovation", "Global"],
    website: "https://solve.mit.edu",
    eligibility: [
      "Social entrepreneurs and innovators worldwide",
      "Must apply to one of the annual challenge tracks",
      "Solutions must be technology-driven and scalable",
      "Early-stage ventures with proven concept preferred",
    ],
    status: "Active",
    deadline: "2027-09-13",
    ecosystem: "USA",
    highlights: [
      "Access to MIT's global network and expertise",
      "Multi-year support with continued funding opportunities",
      "400+ Solver teams from 80+ countries",
    ],
  },
  {
    id: 92,
    name: "Stanford Social Innovation Review Grants",
    organization: "Stanford University",
    logo: "https://placehold.co/100x100/EEE/999?text=S",
    description:
      "Stanford supports social innovation through various programs including the Stanford Social Entrepreneurship Startup Fund and GSB Social Innovation Fellowship. Grants support research, ventures, and community-based projects.",
    fundingAmount: "Up to $50,000",
    category: "University",
    tags: ["Stanford", "Social Innovation", "Fellowship", "Research"],
    website: "https://ssir.org",
    eligibility: [
      "Stanford students, alumni, and affiliated researchers",
      "Projects addressing social or environmental challenges",
      "Must have measurable impact goals",
      "Various programs with different eligibility criteria",
    ],
    status: "Active",
    deadline: "2027-09-18",
    ecosystem: "USA",
    highlights: [
      "Access to Stanford's entrepreneurial ecosystem",
      "SSIR publication platform for thought leadership",
      "Cross-disciplinary innovation support",
    ],
  },
  {
    id: 93,
    name: "Harvard Innovation Labs",
    organization: "Harvard University",
    logo: "https://placehold.co/100x100/EEE/999?text=H",
    description:
      "Harvard Innovation Labs (i-lab) provides venture incubation to Harvard students and alumni. The Venture Incubation Program offers funding, workspace, mentorship, and access to Harvard's network for early-stage startups.",
    fundingAmount: "Up to $100,000",
    category: "University",
    tags: ["Harvard", "Incubation", "Startups", "USA"],
    website: "https://innovationlabs.harvard.edu",
    eligibility: [
      "Current Harvard students (any school) or recent alumni",
      "Must have a venture at idea or early traction stage",
      "Summer-long intensive incubation program",
      "All sectors and industries eligible",
    ],
    status: "Active",
    deadline: "2027-09-23",
    ecosystem: "USA",
    highlights: [
      "Summer Venture Program with dedicated workspace",
      "Access to Harvard's alumni network of 400,000+",
      "President's Innovation Challenge with cash prizes",
    ],
  },
  {
    id: 94,
    name: "Y Combinator Research",
    organization: "Y Combinator",
    logo: "https://placehold.co/100x100/EEE/999?text=Y",
    description:
      "Y Combinator funds early-stage startups through its accelerator program, providing $500K in standard funding. It also runs a research lab supporting open-source and nonprofit technology projects.",
    fundingAmount: "$500,000",
    category: "University",
    tags: ["YC", "Accelerator", "Silicon Valley", "Startups"],
    website: "https://www.ycombinator.com",
    eligibility: [
      "Early-stage startups from any country",
      "Strong technical founding teams preferred",
      "Must relocate to Bay Area for 3-month batch",
      "Two batches per year (January and June)",
    ],
    status: "Active",
    deadline: "2027-09-28",
    ecosystem: "USA",
    highlights: [
      "$500K standard deal ($125K for 7% + $375K on MFN SAFE)",
      "Alumni include Stripe, Airbnb, DoorDash, Reddit",
      "4,000+ companies funded with combined $600B+ valuation",
    ],
  },
  {
    id: 95,
    name: "Oxford Foundry Grant",
    organization: "University of Oxford",
    logo: "https://placehold.co/100x100/EEE/999?text=O",
    description:
      "The Oxford Foundry is the University of Oxford's entrepreneurship centre. It offers accelerator programs, grants, and mentorship to Oxford students and alumni building impactful ventures.",
    fundingAmount: "Up to Â£25,000",
    category: "University",
    tags: ["Oxford", "Entrepreneurship", "UK", "Accelerator"],
    website: "https://www.sbs.ox.ac.uk/oxford-foundry",
    eligibility: [
      "Current Oxford students or alumni within 3 years of graduation",
      "Ventures at idea or early-stage",
      "Must participate in accelerator program",
      "All sectors eligible",
    ],
    status: "Active",
    deadline: "2027-10-03",
    ecosystem: "UK",
    highlights: [
      "SPRINT and L.E.V8 accelerator programs",
      "Access to Oxford's global alumni network",
      "Co-working space and prototyping facilities",
    ],
  },
  {
    id: 96,
    name: "SINE (IIT Bombay)",
    organization: "IIT Bombay",
    logo: "https://placehold.co/100x100/EEE/999?text=I",
    description:
      "Society for Innovation and Entrepreneurship (SINE) at IIT Bombay incubates technology startups. It provides seed funding, lab access, mentorship, and campus infrastructure to startups founded by IIT Bombay community members.",
    fundingAmount: "Up to â‚¹25 Lakhs",
    category: "University",
    tags: ["IIT Bombay", "Incubation", "Tech Startups", "India"],
    website: "https://www.sineiitb.org",
    eligibility: [
      "IIT Bombay students, alumni, or faculty-founded startups",
      "Must be a technology-based startup",
      "External startups can apply for incubation (limited seats)",
      "Must be willing to be based at IIT Bombay campus",
    ],
    status: "Active",
    deadline: "2027-10-08",
    ecosystem: "India",
    highlights: [
      "200+ startups incubated since 2004",
      "Access to IIT Bombay research labs and facilities",
      "Strong alumni-investor network",
    ],
  },
  {
    id: 97,
    name: "FITT (IIT Delhi)",
    organization: "IIT Delhi",
    logo: "https://placehold.co/100x100/EEE/999?text=I",
    description:
      "Foundation for Innovation and Technology Transfer (FITT) at IIT Delhi supports startups through incubation, seed funding, and technology transfer. It bridges academia and industry to commercialize research innovations.",
    fundingAmount: "Up to â‚¹25 Lakhs",
    category: "University",
    tags: ["IIT Delhi", "Tech Transfer", "Incubation", "India"],
    website: "https://fitt-iitd.in",
    eligibility: [
      "IIT Delhi students, alumni, or researchers",
      "Technology startups with strong R&D component",
      "Must undergo incubation at FITT",
      "IP licensing support available for faculty innovations",
    ],
    status: "Active",
    deadline: "2027-10-13",
    ecosystem: "India",
    highlights: [
      "150+ startups incubated",
      "Strong industry partnerships for technology licensing",
      "Access to IIT Delhi's research infrastructure",
    ],
  },
  {
    id: 98,
    name: "IISc STEP",
    organization: "IISc Bangalore",
    logo: "https://placehold.co/100x100/EEE/999?text=I",
    description:
      "Science and Technology Entrepreneurs Park (STEP) at IISc Bangalore provides incubation, seed funding, and mentorship to deep tech startups. It leverages IISc's world-class research to build science-based companies.",
    fundingAmount: "Up to â‚¹10 Lakhs",
    category: "University",
    tags: ["IISc", "Deep Tech", "Research", "Bangalore", "India"],
    website: "https://www.fsid-iisc.in",
    eligibility: [
      "IISc students, alumni, or researchers with tech innovations",
      "Deep tech or science-based startups preferred",
      "Must have technology validated at lab or prototype stage",
      "Both software and hardware startups eligible",
    ],
    status: "Active",
    deadline: "2027-10-18",
    ecosystem: "India",
    highlights: [
      "Access to IISc's cutting-edge research facilities",
      "Located in India's #1 research institution",
      "Strong connections to Bangalore's tech ecosystem",
    ],
  },
  {
    id: 99,
    name: "NUS Enterprise",
    organization: "National University of Singapore",
    logo: "https://placehold.co/100x100/EEE/999?text=N",
    description:
      "NUS Enterprise runs startup incubation, acceleration, and funding programs. The GRIP (Global Resilience Innovation Program) and NUS Overseas Colleges provide funding and global exposure to student and alumni founders.",
    fundingAmount: "Up to SGD 100,000",
    category: "University",
    tags: ["NUS", "Singapore", "Incubation", "Global"],
    website: "https://enterprise.nus.edu.sg",
    eligibility: [
      "NUS students, alumni, or researchers",
      "Open to international teams through specific programs",
      "Must participate in structured incubation program",
      "All sectors eligible, deep tech focus for some programs",
    ],
    status: "Active",
    deadline: "2027-10-23",
    ecosystem: "Singapore",
    highlights: [
      "NUS ranked #1 in Asia for startups",
      "Global programs across 15+ countries",
      "3,000+ startups supported since inception",
    ],
  },
  {
    id: 100,
    name: "ETH Zurich Pioneer Fellowship",
    organization: "ETH Zurich",
    logo: "https://placehold.co/100x100/EEE/999?text=E",
    description:
      "The ETH Pioneer Fellowship provides CHF 150,000 in equity-free funding and 18 months of coaching to ETH Zurich spin-offs. It supports deep tech entrepreneurs turning ETH research into market-ready products.",
    fundingAmount: "CHF 150,000",
    category: "University",
    tags: ["ETH Zurich", "Deep Tech", "Spin-off", "Switzerland"],
    website: "https://entrepreneurship.ethz.ch/startups-spinoffs/find-offers-programs-space-grants-for-entrepreneurs/pioneer-fellowship.html",
    eligibility: [
      "ETH Zurich students, alumni, or researchers",
      "Must have technology originating from ETH research",
      "Venture must be in pre-seed or seed stage",
      "Two application rounds per year",
    ],
    status: "Active",
    deadline: "2027-10-28",
    ecosystem: "Switzerland",
    highlights: [
      "Equity-free - no dilution",
      "18-month coaching and mentorship program",
      "ETH spin-offs have raised CHF 5B+ in total funding",
    ],
  },
];
