import type { Grant } from "./grantsData";

export const grantsAccelerator: Grant[] = [
  {
    id: 101,
    name: "Techstars Accelerator",
    organization: "Techstars",
    logo: "https://placehold.co/100x100/EEE/999?text=T",
    description:
      "Techstars runs 3-month accelerator programs globally across industries. Startups receive $120K in funding, mentorship from thousands of mentors, and access to Techstars' worldwide network of founders and investors.",
    fundingAmount: "$120,000",
    category: "Accelerator",
    tags: ["Accelerator", "Mentorship", "Global", "Startups"],
    website: "https://www.techstars.com",
    eligibility: [
      "Early-stage startups from any country and sector",
      "Must relocate to program city for 3 months",
      "Strong founding team required",
      "Acceptance rate ~1%",
    ],
    status: "Active",
    deadline: "2026-06-05",
    ecosystem: "USA",
    highlights: [
      "4,000+ companies funded globally",
      "$120K for 6% common stock",
      "Programs in 10+ cities worldwide",
    ],
  },
  {
    id: 102,
    name: "500 Global Accelerator",
    organization: "500 Global",
    logo: "https://placehold.co/100x100/EEE/999?text=5",
    description:
      "500 Global (formerly 500 Startups) invests in early-stage startups through its accelerator and seed programs. It has invested in 2,800+ companies across 80+ countries with a focus on diverse, global founding teams.",
    fundingAmount: "$150,000",
    category: "Accelerator",
    tags: ["Seed", "Global", "Diverse Founders", "Accelerator"],
    website: "https://500.co",
    eligibility: [
      "Early-stage startups with product-market fit or early traction",
      "Global applications welcome - 80+ countries represented",
      "4-month accelerator program in San Francisco",
      "Focus on fintech, edtech, healthtech, and marketplaces",
    ],
    status: "Active",
    deadline: "2026-06-10",
    ecosystem: "USA",
    highlights: [
      "2,800+ portfolio companies",
      "$150K standard investment",
      "36 unicorn companies in portfolio",
    ],
  },
  {
    id: 103,
    name: "Antler Residency Program",
    organization: "Antler",
    logo: "https://placehold.co/100x100/EEE/999?text=A",
    description:
      "Antler is a global venture builder and early-stage VC. Its residency program helps exceptional individuals find co-founders, build ventures, and raise pre-seed funding - all within a 3-6 month program.",
    fundingAmount: "$100,000",
    category: "Accelerator",
    tags: ["Venture Builder", "Pre-seed", "Co-founder Matching", "Global"],
    website: "https://www.antler.co",
    eligibility: [
      "Exceptional individuals - engineers, operators, domain experts",
      "No existing startup required - find co-founders during the program",
      "Programs in 27 cities across 6 continents",
      "Monthly stipend provided during residency",
    ],
    status: "Active",
    deadline: "2026-06-15",
    ecosystem: "Global",
    highlights: [
      "Co-founder matching built into the program",
      "Invested in 1,000+ startups globally",
      "Programs in India (Bangalore), Singapore, London, NYC, and more",
    ],
  },
  {
    id: 104,
    name: "Plug and Play Accelerator",
    organization: "Plug and Play",
    logo: "https://placehold.co/100x100/EEE/999?text=P",
    description:
      "Plug and Play is Silicon Valley's largest innovation platform, connecting startups with corporations for pilots, partnerships, and funding. Its accelerator provides equity-free programs with direct corporate access.",
    fundingAmount: "Up to $500,000",
    category: "Accelerator",
    tags: ["Corporate Innovation", "Silicon Valley", "B2B", "Accelerator"],
    website: "https://www.plugandplaytechcenter.com",
    eligibility: [
      "B2B startups with technology products",
      "Must be relevant to one of Plug and Play's industry verticals",
      "Global startups welcome",
      "Equity-free accelerator program; investment separate",
    ],
    status: "Active",
    deadline: "2026-06-20",
    ecosystem: "USA",
    highlights: [
      "Equity-free accelerator program",
      "550+ corporate partners including major enterprises",
      "Alumni include PayPal, Dropbox, LendingClub",
    ],
  },
  {
    id: 105,
    name: "MassChallenge",
    organization: "MassChallenge",
    logo: "https://placehold.co/100x100/EEE/999?text=M",
    description:
      "MassChallenge is a global zero-equity accelerator supporting startups across all industries. Top-performing startups win cash awards from a prize pool, and all participants get mentorship, corporate connections, and workspace.",
    fundingAmount: "Up to $100,000 (equity-free)",
    category: "Accelerator",
    tags: ["Zero Equity", "Competition", "Global", "Accelerator"],
    website: "https://masschallenge.org",
    eligibility: [
      "Early-stage startups from any industry and country",
      "Must have a working prototype or early revenue",
      "4-month accelerator in Boston, Israel, Mexico, or Switzerland",
      "No equity taken - competition-based prizes",
    ],
    status: "Active",
    deadline: "2026-06-25",
    ecosystem: "USA",
    highlights: [
      "Zero equity - keeps 100% of your company",
      "3,600+ startups accelerated since 2010",
      "Alumni have raised $8.7B+ in total funding",
    ],
  },
  {
    id: 106,
    name: "Seedstars Program",
    organization: "Seedstars",
    logo: "https://placehold.co/100x100/EEE/999?text=S",
    description:
      "Seedstars supports startups in emerging markets through investment, acceleration, and capacity building. It runs competitions and programs across 90+ countries, connecting founders with investors and corporate partners.",
    fundingAmount: "Up to $500,000",
    category: "Accelerator",
    tags: ["Emerging Markets", "Impact", "Global", "Investment"],
    website: "https://www.seedstars.com",
    eligibility: [
      "Startups from emerging and frontier markets",
      "Must be less than 5 years old with a scalable tech solution",
      "Annual Seedstars World competition across 90+ countries",
      "Focus on fintech, edtech, healthtech in developing economies",
    ],
    status: "Active",
    deadline: "2026-06-30",
    ecosystem: "Global",
    highlights: [
      "Operates in 90+ emerging markets",
      "Annual Seedstars Summit in Switzerland",
      "$500K grand prize for Seedstars World winner",
    ],
  },
  {
    id: 107,
    name: "SOSV Accelerator Programs",
    organization: "SOSV",
    logo: "https://placehold.co/100x100/EEE/999?text=S",
    description:
      "SOSV operates accelerators including HAX (hardware), IndieBio (biotech), and Chinaccelerator (cross-border). It invests in deep tech startups with intensive 3-6 month programs and follow-on funding.",
    fundingAmount: "$100,000-$250,000",
    category: "Accelerator",
    tags: ["Deep Tech", "Hardware", "Biotech", "Accelerator"],
    website: "https://sosv.com",
    eligibility: [
      "Deep tech startups: hardware (HAX), biotech (IndieBio), cross-border (Chinaccelerator)",
      "Must participate in program-specific accelerator",
      "Strong technical team required",
      "Global applicants welcome",
    ],
    status: "Active",
    deadline: "2026-07-05",
    ecosystem: "USA",
    highlights: [
      "1,200+ companies funded",
      "HAX is the world's largest hardware accelerator",
      "IndieBio focuses on biotech and synthetic biology",
    ],
  },
  {
    id: 108,
    name: "Founders Factory Accelerator",
    organization: "Founders Factory",
    logo: "https://placehold.co/100x100/EEE/999?text=F",
    description:
      "Founders Factory partners with large corporations to build and accelerate startups. It offers 6-month programs with dedicated engineering, design, and growth teams to help startups scale, plus investment of up to £250K.",
    fundingAmount: "Up to £250,000",
    category: "Accelerator",
    tags: ["Corporate Partnership", "UK", "Scaling", "Accelerator"],
    website: "https://foundersfactory.com",
    eligibility: [
      "Early-stage startups aligned with corporate partner verticals",
      "Must be based in or willing to relocate to London",
      "Sectors: health, education, media, sustainability",
      "Post-MVP startups with some traction preferred",
    ],
    status: "Active",
    deadline: "2026-07-10",
    ecosystem: "UK",
    highlights: [
      "Dedicated engineering and design support",
      "Corporate partners include L'OrÃ©al, Aviva, Guardian",
      "Also builds ventures from scratch (studio model)",
    ],
  },
  {
    id: 109,
    name: "Entrepreneur First (EF)",
    organization: "Entrepreneur First",
    logo: "https://placehold.co/100x100/EEE/999?text=E",
    description:
      "Entrepreneur First invests in individuals before they have an idea or co-founder. Its 6-month program helps talented people find co-founders, develop ideas, and raise funding - all before incorporating a company.",
    fundingAmount: "$100,000",
    category: "Accelerator",
    tags: ["Pre-idea", "Co-founder Matching", "UK", "Global"],
    website: "https://www.joinef.com",
    eligibility: [
      "Exceptional individuals - no startup or idea needed to apply",
      "Engineers, PhDs, industry experts, and technical operators",
      "Programs in London, Bangalore, Singapore, Toronto, Berlin",
      "Must commit full-time to the 6-month program",
    ],
    status: "Active",
    deadline: "2026-07-15",
    ecosystem: "UK",
    highlights: [
      "Invest at the individual level - before a company exists",
      "800+ companies built since 2011",
      "Combined portfolio valuation of $10B+",
    ],
  },
  {
    id: 110,
    name: "Chiratae Ventures Sonic Program",
    organization: "Chiratae Ventures",
    logo: "https://placehold.co/100x100/EEE/999?text=C",
    description:
      "Chiratae Ventures' Sonic Program is India's leading early-stage startup program. It provides seed funding, mentorship from successful entrepreneurs, and access to Chiratae's network for Indian tech startups.",
    fundingAmount: "Up to ₹1 Crore",
    category: "Accelerator",
    tags: ["India", "Seed", "Tech Startups", "VC"],
    website: "https://chiratae.com",
    eligibility: [
      "Indian tech startups at pre-seed or seed stage",
      "Strong founding team with technical background",
      "Must have an MVP or working prototype",
      "Sectors: SaaS, consumer tech, fintech, healthtech",
    ],
    status: "Active",
    deadline: "2026-07-20",
    ecosystem: "India",
    highlights: [
      "India's longest-running VC firm (since 2006)",
      "Portfolio includes Myntra, Lenskart, Flipkart",
      "Mentor network of 100+ successful founders",
    ],
  },
  {
    id: 141,
    name: "Google for Startups Cloud Program",
    organization: "Google",
    logo: "https://placehold.co/100x100/EEE/999?text=G",
    description:
      "Google for Startups Cloud Program provides cloud credits, technical mentorship, and business support to early-stage startups. Eligible startups receive up to $200,000 in Google Cloud credits over 2 years.",
    fundingAmount: "Up to $200,000 cloud credits",
    category: "Accelerator",
    tags: ["Google Cloud", "Credits", "Startups", "Technical Support"],
    website: "https://cloud.google.com/startup",
    eligibility: [
      "Startups that are seed to Series A stage",
      "Must be associated with an approved accelerator, incubator, or VC",
      "Cannot be a current Google Cloud customer at enterprise tier",
      "Must not have previously received Google Cloud startup credits",
    ],
    status: "Active",
    deadline: "2026-07-25",
    ecosystem: "Global",
    highlights: [
      "$200K credits over 2 years for approved startups",
      "Technical mentorship from Google engineers",
      "Access to Google's startup network and events",
    ],
  },
  {
    id: 142,
    name: "AWS Activate",
    organization: "Amazon Web Services",
    logo: "https://placehold.co/100x100/EEE/999?text=A",
    description:
      "AWS Activate provides startups with free cloud credits, technical support, and training to build on AWS. The program offers different tiers from self-funded startups to VC-backed companies with up to $100,000 in credits.",
    fundingAmount: "Up to $100,000 credits",
    category: "Accelerator",
    tags: ["AWS", "Cloud Credits", "Startups", "Infrastructure"],
    website: "https://aws.amazon.com/activate",
    eligibility: [
      "Startups at any stage - self-funded to Series A",
      "Must not have previously exceeded $100K in AWS credits",
      "Portfolio tier available through approved VCs and accelerators",
      "Self-service tier: $1,000 credits for any startup",
    ],
    status: "Active",
    deadline: "2026-07-30",
    ecosystem: "Global",
    highlights: [
      "Up to $100K credits through VC/accelerator partnerships",
      "Free AWS Business Support for 1 year",
      "Self-service tier available to all startups globally",
    ],
  },
  {
    id: 143,
    name: "Microsoft for Startups Founders Hub",
    organization: "Microsoft",
    logo: "https://placehold.co/100x100/EEE/999?text=M",
    description:
      "Microsoft for Startups Founders Hub provides free Azure credits, GitHub Enterprise, Visual Studio, and technical mentorship. It's open to all startups globally, regardless of funding stage or background.",
    fundingAmount: "Up to $150,000 credits",
    category: "Accelerator",
    tags: ["Microsoft", "Azure", "GitHub", "Startups"],
    website: "https://www.microsoft.com/en-us/startups",
    eligibility: [
      "Any startup at any stage - no VC backing required",
      "Must be building a software-based product",
      "Open to startups worldwide",
      "Credits scale up as startup progresses through milestones",
    ],
    status: "Active",
    deadline: "2026-08-04",
    ecosystem: "Global",
    highlights: [
      "No application gatekeeping - open to all startups",
      "Credits: $1K → $5K → $25K → $150K as you grow",
      "Includes OpenAI API credits for AI startups",
    ],
  },
  {
    id: 144,
    name: "Cisco Innovation Fund",
    organization: "Cisco",
    logo: "https://placehold.co/100x100/EEE/999?text=C",
    description:
      "Cisco's Country Digital Acceleration and Innovation Fund invests in startups and projects driving digital transformation. It supports networking, security, IoT, and collaboration technology innovations worldwide.",
    fundingAmount: "Up to $250,000",
    category: "Accelerator",
    tags: ["Cisco", "Networking", "IoT", "Security", "Digital"],
    website: "https://www.cisco.com/site/us/en/about/purpose/social-impact/cisco-foundation.html",
    eligibility: [
      "Startups with networking, security, or IoT innovations",
      "Must align with Cisco's strategic technology areas",
      "Programs available in 40+ countries",
      "Both investment and grant-based programs",
    ],
    status: "Active",
    deadline: "2026-08-09",
    ecosystem: "Global",
    highlights: [
      "$1B+ invested through Country Digital Acceleration",
      "Co-innovation opportunities with Cisco engineering",
      "Global reach across 40+ countries",
    ],
  },
  {
    id: 145,
    name: "IBM Hyper Protect Accelerator",
    organization: "IBM",
    logo: "https://placehold.co/100x100/EEE/999?text=I",
    description:
      "IBM's startup programs provide cloud credits, technical mentorship, and go-to-market support. The Hyper Protect Accelerator focuses on healthcare and fintech startups needing enterprise-grade security and compliance.",
    fundingAmount: "Up to $120,000",
    category: "Accelerator",
    tags: ["IBM", "Healthcare", "Fintech", "Enterprise", "Security"],
    website: "https://developer.ibm.com/startups",
    eligibility: [
      "Early-stage startups in healthcare, fintech, or enterprise tech",
      "Must require enterprise-grade security and compliance",
      "IBM Cloud credits and technical support included",
      "Partnership track for commercial collaboration",
    ],
    status: "Active",
    deadline: "2026-08-14",
    ecosystem: "USA",
    highlights: [
      "$120K in IBM Cloud credits",
      "Focus on confidential computing and data privacy",
      "Enterprise customer introductions",
    ],
  },
  {
    id: 146,
    name: "Salesforce Ventures Impact Fund",
    organization: "Salesforce",
    logo: "https://placehold.co/100x100/EEE/999?text=S",
    description:
      "Salesforce Ventures' Impact Fund invests in enterprise cloud startups focused on sustainability, equality, and social impact. It provides funding plus access to Salesforce's ecosystem of customers and partners.",
    fundingAmount: "Up to $500,000",
    category: "Accelerator",
    tags: ["Salesforce", "Impact", "Enterprise", "Cloud", "ESG"],
    website: "https://www.salesforce.com/ventures",
    eligibility: [
      "Enterprise cloud startups with social or environmental mission",
      "Must build on or integrate with Salesforce platform",
      "Seed to Series A stage preferred",
      "Focus on workforce development, sustainability, and equality",
    ],
    status: "Active",
    deadline: "2026-08-19",
    ecosystem: "USA",
    highlights: [
      "$100M+ Impact Fund for mission-driven startups",
      "Access to Salesforce's 150,000+ customer base",
      "Salesforce Accelerate program for integration support",
    ],
  },
  {
    id: 147,
    name: "SAP.iO Foundry Program",
    organization: "SAP",
    logo: "https://placehold.co/100x100/EEE/999?text=S",
    description:
      "SAP.iO runs accelerator foundries in 10+ cities worldwide, supporting B2B startups building on or integrating with SAP technologies. It provides equity-free support, SAP technology access, and customer introductions.",
    fundingAmount: "Up to €250,000 in value",
    category: "Accelerator",
    tags: ["SAP", "B2B", "Enterprise", "ERP", "Accelerator"],
    website: "https://www.sap.com/partners.html",
    eligibility: [
      "B2B startups with solutions complementing SAP's ecosystem",
      "Must be willing to integrate with SAP technologies",
      "Programs run 3-6 months in cities like Berlin, Munich, NYC, Singapore",
      "Both early-stage and growth-stage programs available",
    ],
    status: "Active",
    deadline: "2026-08-24",
    ecosystem: "Global",
    highlights: [
      "Equity-free accelerator - no dilution",
      "Direct access to SAP's 440,000+ enterprise customers",
      "Foundries in 10+ cities worldwide",
    ],
  },
  {
    id: 148,
    name: "Qualcomm Innovation Fellowship",
    organization: "Qualcomm",
    logo: "https://placehold.co/100x100/EEE/999?text=Q",
    description:
      "The Qualcomm Innovation Fellowship (QIF) awards PhD students working on breakthrough research in mobile, wireless, computing, and semiconductor technologies. Fellows receive funding and mentorship from Qualcomm engineers.",
    fundingAmount: "Up to $100,000",
    category: "Accelerator",
    tags: ["Qualcomm", "PhD", "Mobile", "Wireless", "Research"],
    website: "https://www.qualcomm.com/research/university-relations/innovation-fellowship",
    eligibility: [
      "PhD students at approved universities (teams of 2 students)",
      "Research in mobile, wireless, AI, XR, or semiconductor technologies",
      "Must propose research aligned with Qualcomm's interest areas",
      "Annual program with October deadline",
    ],
    status: "Active",
    deadline: "2026-08-29",
    ecosystem: "USA",
    highlights: [
      "$100K shared between 2 PhD students per team",
      "Direct mentorship from Qualcomm Research engineers",
      "Finalists present at Qualcomm's annual research event",
    ],
  },
  {
    id: 149,
    name: "Adobe Fund for Design",
    organization: "Adobe",
    logo: "https://placehold.co/100x100/EEE/999?text=A",
    description:
      "The Adobe Fund for Design supports projects that expand access to creativity and design education. It funds nonprofits, universities, and individuals creating tools, curricula, and programs that empower underrepresented communities.",
    fundingAmount: "Up to $25,000",
    category: "Accelerator",
    tags: ["Adobe", "Design", "Education", "Creativity", "Diversity"],
    website: "https://developer.adobe.com/fund-for-design/",
    eligibility: [
      "Nonprofits, educational institutions, and community organizations",
      "Projects expanding access to design and creativity tools",
      "Must focus on underrepresented or underserved communities",
      "Rolling applications accepted",
    ],
    status: "Active",
    deadline: "2026-09-03",
    ecosystem: "Global",
    highlights: [
      "Focus on design education and creative empowerment",
      "Adobe Creative Cloud licenses for funded programs",
      "Supports diversity in design and tech fields",
    ],
  },
  {
    id: 150,
    name: "Bosch Research and Technology Grants",
    organization: "Robert Bosch Stiftung",
    logo: "https://placehold.co/100x100/EEE/999?text=B",
    description:
      "The Robert Bosch Foundation funds research and innovation projects in healthcare, education, sustainability, and international understanding. It also supports startups through Bosch's corporate venture activities and research partnerships.",
    fundingAmount: "Up to €200,000",
    category: "Accelerator",
    tags: ["Bosch", "Sustainability", "Healthcare", "Education", "EU"],
    website: "https://www.bosch-stiftung.de/en",
    eligibility: [
      "Researchers, innovators, and social entrepreneurs",
      "Projects aligned with Bosch Foundation's focus areas",
      "Open to international applicants with EU/German partnerships",
      "Both individual and institutional applications accepted",
    ],
    status: "Active",
    deadline: "2026-09-08",
    ecosystem: "Germany",
    highlights: [
      "One of Europe's largest corporate foundations",
      "€1.2B+ distributed since 1964",
      "Supports research, education, and international dialogue",
    ],
  },
  {
    id: 157,
    name: "Y Combinator",
    organization: "Y Combinator",
    logo: "https://placehold.co/100x100/EEE/999?text=Y",
    description:
      "Y Combinator runs three-month accelerator batches in San Francisco, investing in every accepted startup on the same standard terms and connecting founders to its General Partners, alumni network, and demo day investors.",
    fundingAmount: "$500,000",
    category: "Accelerator",
    tags: ["Accelerator", "Seed", "Demo Day", "Global"],
    website: "https://www.ycombinator.com/apply",
    eligibility: [
      "Startups at any stage, anywhere in the world",
      "YC invests in US, Canada, Cayman, or Singapore-incorporated companies",
      "Online application followed by an interview for shortlisted teams",
      "Highly competitive - decisions typically same-day as interview",
    ],
    status: "Active",
    deadline: "2026-07-27",
    ecosystem: "USA",
    highlights: [
      "$125K for 7% equity + $375K uncapped MFN SAFE, no program fees",
      "3-day kickoff plus weekly group office hours during the batch",
      "Access to the full YC alumni and investor network post-batch",
    ],
  },
  {
    id: 158,
    name: "NVIDIA Inception Program",
    organization: "NVIDIA",
    logo: "https://placehold.co/100x100/EEE/999?text=N",
    description:
      "A free membership program for AI startups that provides cloud credits, discounted hardware/software, technical training via the NVIDIA Deep Learning Institute, and exposure to a global network of investors, with no application, membership, or equity fees.",
    fundingAmount: "Free membership + cloud credits",
    category: "Accelerator",
    tags: ["AI", "Cloud Credits", "No Equity", "Global"],
    website: "https://www.nvidia.com/en-us/startups/",
    eligibility: [
      "Startups building AI, data science, or accelerated-computing products",
      "No funding round or revenue minimum to apply",
      "Free to join - no equity or membership fees",
      "Must keep product/company details updated in the Inception portal",
    ],
    status: "Active",
    deadline: "2027-01-31",
    ecosystem: "Global",
    highlights: [
      "No equity or fees taken - free membership",
      "Free cloud credits from NVIDIA and partners (e.g. up to $150K via Nebius)",
      "Preferred pricing on NVIDIA hardware/software plus DLI training",
    ],
  },
];
